"use client";

import { useEffect } from "react";
import { NativeLink as Link } from "./native-link";
import { SiteFooter, SiteHeader } from "./site";
import { leadershipProfiles as leaders } from "../data/people";

const clients=[
  {name:"Globus Medical",logo:"/clients/globus-medical.png",tag:"PRODUCTION · MEDICAL DEVICES",summary:"A 5,000-user, fully on-prem deployment with cited outputs, customer-controlled infrastructure, and human review retained.",metric:"4–5×",metricLabel:"reported review acceleration",facts:["5,000 users","Fully on-prem","Production"]},
  {name:"Micron",logo:"/clients/micron.png",tag:"PAID POC · SEMICONDUCTOR",summary:"A paid proof of concept evaluating a governed engineering loop—simulate, review, revise, and re-run—inside the agreed boundary.",metric:"04",metricLabel:"agent-loop stages",facts:["Paid proof of concept","Governed workflow","Semiconductor"]},
  {name:"Dubai CommerCity",logo:"/clients/dubai-commercity.svg",tag:"PUBLIC-LIVE · UAE GOVERNMENT FREE ZONE",summary:"Founders served on the public website, with answers constrained to approved official sources and available around the clock.",metric:"24/7",metricLabel:"on the public site",facts:["Public-facing AI","Official sources","UAE"]}
];

const products=[
  {n:"01",eyebrow:"ENTERPRISE SEARCH · GROUNDED MODE",title:"Just ask, in plain English.",body:"No folders to dig through. Grounded-answer mode routes each question across permissioned company knowledge, attributes the sources it uses, and can refuse when evidence is insufficient.",stat:"CITED",statLabel:"grounded-answer mode",image:"/product/enterprise-search.webp",href:"/platform/know"},
  {n:"02",eyebrow:"ENTERPRISE SEARCH · DATABASE MODE",title:"From a question to a chart.",body:"Describe the number you need. The agent can prepare and run an approved query against a connected database, visualise the result, and export it with the control model defined for that deployment.",stat:"LIVE",statLabel:"connected database",image:"/product/database-mode.webp",href:"/platform/know"},
  {n:"03",eyebrow:"AGENT BUILDER",title:"Agents that take action.",body:"Connect approved systems, tools, and specialist agents in a visual workflow. Human approvals stay exactly where the business requires them.",stat:"HITL",statLabel:"approval gates",image:"/product/agent-builder.webp",href:"/platform/build"},
  {n:"04",eyebrow:"AI WORKSPACE",title:"One place for every agent.",body:"Your agents, multi-agent workflows, and available platform agents—published and governed inside one enterprise workspace.",stat:"ONE",statLabel:"governed workspace",image:"/product/ai-workspace.webp",href:"/platform/work"}
];

const verticals=[
  {n:"01",name:"Healthcare & medical devices",proof:"5,000 users · fully on-prem · production",headline:"Compliance first. Intelligence second. Both by design.",body:"Surgical case preparation, regulatory intelligence, CAPA support, and clinical enablement—grounded in controlled documents, permissioned by role, and fully auditable.",workflows:["Surgical case preparation","Regulatory intelligence","Quality & CAPA","Clinical enablement"],metric:"4–5×",metricLabel:"faster research reviews",href:"/industries/healthcare"},
  {n:"02",name:"Semiconductor",proof:"Governed engineering loop · paid POC",headline:"Where IP is the company, sovereignty is the product.",body:"The controlled proof-of-concept keeps design and process knowledge inside the agreed boundary while the workflow simulates, reviews, revises, and re-runs with recorded decision points.",workflows:["Design-doc navigation","Process knowledge","Engineering review","Multi-agent simulation"],metric:"04",metricLabel:"recorded workflow stages",href:"/industries/semiconductor"},
  {n:"03",name:"Government & public sector",proof:"Public website · official regulations · UAE",headline:"Public answers that can be defended line by line.",body:"Citizen and founder guidance grounded only in official regulations, available 24/7, deployed in-region, and structured for the audit and language requirements of public institutions.",workflows:["Official-information Q&A","Founder advisory","Program navigation","Regulatory guidance"],metric:"24/7",metricLabel:"grounded public service",href:"/industries/government"}
];

const clamp=(v:number)=>Math.max(0,Math.min(1,v));
function AgencyMotion(){useEffect(()=>{const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const reveals=[...document.querySelectorAll<HTMLElement>("[data-agency-reveal]")];const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){(e.target as HTMLElement).classList.add("is-in");io.unobserve(e.target)}}),{threshold:.12,rootMargin:"0px 0px -40px"});reveals.forEach(x=>io.observe(x));const horizontals=[...document.querySelectorAll<HTMLElement>("[data-agency-horizontal]")];const architectures=[...document.querySelectorAll<HTMLElement>("[data-agency-architecture]")];let raf=0,dirty=true;const frame=()=>{if(dirty){dirty=false;horizontals.forEach(section=>{const r=section.getBoundingClientRect(),p=clamp(-r.top/Math.max(1,r.height-innerHeight)),stage=section.querySelector<HTMLElement>("[data-agency-stage]")!,track=section.querySelector<HTMLElement>("[data-agency-track]")!;if(!stage||!track)return;const max=Math.max(0,track.scrollWidth-stage.clientWidth);track.style.transform=innerWidth<800||reduced?"none":`translate3d(${-p*max}px,0,0)`;section.style.setProperty("--agency-p",String(p))});architectures.forEach(section=>{const r=section.getBoundingClientRect(),p=clamp((innerHeight*.65-r.top)/Math.max(1,r.height+innerHeight*.3));section.style.setProperty("--arch-p",String(reduced?1:p))})}raf=requestAnimationFrame(frame)};const mark=()=>{dirty=true};addEventListener("scroll",mark,{passive:true});addEventListener("resize",mark,{passive:true});raf=requestAnimationFrame(frame);return()=>{cancelAnimationFrame(raf);removeEventListener("scroll",mark);removeEventListener("resize",mark);io.disconnect()}},[]);return null}

function AgencyHero(){return <section className="agency-hero"><div className="agency-hero-copy"><p>CORPORATE GPT · SOVEREIGN ENTERPRISE AI</p><h1>AI inside your walls.<br/>Under <em>your control.</em></h1><span>Enterprise AI and custom agents, deployed inside your data centre or cloud tenant—so documents, data, and learned assets remain within the boundary and data paths agreed for that deployment.</span><div className="agency-actions"><Link href="/briefing">Request a briefing</Link><Link href="/platform">Explore the platform ↗</Link></div><div className="agency-hero-stats"><b>03 <span>regulated sectors represented</span></b><b>12 <span>week reference rollout</span></b><b>−60% <span>modeled total cost</span></b></div></div><div className="sovereign-object" role="img" aria-label="Corporate GPT architecture places employees, agents, and customer-specific AI inside a customer-controlled boundary with documented data paths"><div className="object-boundary"><span>YOUR ORGANISATION&apos;S BOUNDARY</span><div className="object-ring ring-a"><i>EMPLOYEES</i></div><div className="object-ring ring-b"><i>AI AGENTS</i></div><div className="object-ring ring-c"><i>CORPORATE LLM</i></div><div className="object-core"><img src="/brand/neurologic-logogram-white.png" alt="" width="150" height="134"/><b>CORPORATE GPT</b><small>CONTROLLED PATHS</small></div><p>BOUNDARY SET PER DEPLOYMENT</p></div></div><div className="mobile-scroll-cue" aria-hidden="true"><span>Scroll to enter the system</span><i/></div></section>}

export function ClientProof({expanded=false}:{expanded?:boolean}){return <section className={`client-proof ${expanded?"expanded":""}`}><div className="agency-section-head" data-agency-reveal><div><p>NAMED CUSTOMER EVIDENCE</p><h2>Proof where the reviews <em>are hardest.</em></h2></div><span>Production, public-live, and paid-POC evidence are labeled separately—because those statuses are not interchangeable.</span></div><div className="client-case-grid" data-mobile-track role="region" aria-label="Customer evidence cards" tabIndex={0}>{clients.map((c,i)=><article key={c.name} data-agency-reveal><div className="client-case-top"><span>0{i+1}</span><small>{c.tag}</small></div><div className="client-card-logo"><img src={c.logo} alt={`${c.name} logo`} loading="lazy" decoding="async"/></div><h3>{c.name}</h3><p>{c.summary}</p><div className="client-metric"><strong>{c.metric}</strong><span>{c.metricLabel}</span></div><div className="client-facts">{c.facts.map(x=><b key={x}>{x}</b>)}</div>{expanded&&<Link href="/briefing">Discuss this evidence ↗</Link>}</article>)}</div></section>}

function ArchitectureStory(){const layers=[{name:"AI applications",desc:"Employee-facing apps & workflows",owner:"YOU BUILD"},{name:"AI agents",desc:"Composed, governed, orchestrated",owner:"WE BUILD · YOU BUILD"},{name:"Corporate LLM",desc:"Neurologic platform IP + your knowledge",owner:"WE PROVIDE & BUILD"},{name:"GPU servers",desc:"Accelerated inference and learning",owner:"YOU OWN · WE RESELL"},{name:"Data centre / cloud",desc:"On-premise or your tenant",owner:"YOU OWN"}];return <section className="architecture-story" data-agency-architecture><div className="architecture-copy" data-agency-reveal><p>SOVEREIGN AI ARCHITECTURE</p><h2>The whole stack—<em>yours or ours.</em></h2><span>Your deployment keeps infrastructure, data, and learned assets under the control model agreed for your environment. Your teams build applications and agents on top—or we build with you.</span><Link href="/deployment">Explore deployment architecture ↗</Link></div><div className="architecture-stack">{layers.map((x,i)=><div className={`arch-layer arch-${i}`} key={x.name} style={{"--layer":i} as React.CSSProperties}><span>0{i+1}</span><div><h3>{x.name}</h3><p>{x.desc}</p></div><b>{x.owner}</b></div>)}<small>YOUR SECURITY BOUNDARY</small></div></section>}

function ProductHorizontal(){return <section className="agency-horizontal" data-agency-horizontal><div className="agency-horizontal-stage" data-agency-stage><div className="product-story-head"><p>THE PRODUCT · REAL INTERFACES</p><h2>From a question to <em>an outcome.</em></h2><span>Swipe through the product</span></div><div className="agency-product-track" data-agency-track data-mobile-track role="region" aria-label="Corporate GPT product interfaces" tabIndex={0}>{products.map(p=><article key={p.n}><div className="product-panel-copy"><span>{p.n} / 04</span><small>{p.eyebrow}</small><h3>{p.title}</h3><p>{p.body}</p><div><strong>{p.stat}</strong><em>{p.statLabel}</em></div><Link href={p.href}>Explore this capability ↗</Link></div><div className="product-shot"><img src={p.image} alt={`${p.title} Corporate GPT product interface`} loading="lazy" decoding="async"/></div></article>)}</div><div className="agency-horizontal-progress"><i/></div></div></section>}

function CorporateLLM(){return <section className="corporate-llm"><div className="agency-section-head" data-agency-reveal><div><p>CUSTOMER-SPECIFIC INTELLIGENCE</p><h2>Not generic context.<br/><em>Your operating knowledge.</em></h2></div><span>Customer-specific retrieval, memory, configurations, evaluation sets, and approved adapters can improve inside the agreed environment.</span></div><div className="llm-equation" data-agency-reveal role="img" aria-label="Open foundation model plus Neurologic platform capabilities plus customer knowledge produces customer-specific intelligence governed by licenses and the customer agreement"><div><span>01</span><h3>Foundation model</h3><p>Selected under its applicable license.</p></div><b>+</b><div><span>02</span><h3>Neurologic platform IP</h3><p>Grounding, orchestration, controls, and evaluation.</p></div><b>+</b><div><span>03</span><h3>Your knowledge</h3><p>Your approved language, policies, documents, and decisions.</p></div><b>=</b><div className="owned"><span>04</span><h3>Customer-specific intelligence</h3><p>Rights follow the model licenses and signed customer agreement.</p></div></div></section>}

function AgentFlow(){return <section className="agent-flow"><div className="agency-section-head" data-agency-reveal><div><p>AGENTS THAT TAKE ACTION</p><h2>From workflows to outcomes—<em>with you in control.</em></h2></div><span>Not a rogue agent. A diligent digital colleague that asks permission when the work matters.</span></div><div className="flow-rail" data-agency-reveal><div><span>01</span><i>↯</i><h3>Trigger</h3><p>From ERP, CRM, service desk, or schedule.</p></div><b>→</b><div><span>02</span><i>◎</i><h3>Multi-step work</h3><p>Specialist agents coordinate tools and systems.</p></div><b>→</b><div className="approval"><span>03</span><i>✓</i><h3>Approval gate</h3><p>Human sign-off where policy requires it.</p></div><b>→</b><div><span>04</span><i>◆</i><h3>Done</h3><p>Outcome delivered, logged, and attributable.</p></div></div></section>}

export function VerticalProof({full=false}:{full?:boolean}){return <section className={`vertical-proof ${full?"full":""}`}><div className="agency-section-head" data-agency-reveal><div><p>VERTICAL DEPTH</p><h2>Built where generic AI <em>cannot operate.</em></h2></div><span>Three regulated sectors, each with a distinct workflow, risk model, deployment status, and proof standard.</span></div><div className="vertical-list" data-mobile-track role="region" aria-label="Industry evidence cards" tabIndex={0}>{verticals.map(v=><article key={v.name} data-agency-reveal><div className="vertical-number">{v.n}</div><div className="vertical-main"><small>{v.proof}</small><h3>{v.name}</h3><h4>{v.headline}</h4><p>{v.body}</p><div>{v.workflows.map(x=><span key={x}>{x}</span>)}</div><Link href={v.href}>Explore the vertical ↗</Link></div><div className="vertical-metric"><strong>{v.metric}</strong><span>{v.metricLabel}</span><div className="vertical-evidence-key"><b>ENGAGEMENT STATUS</b><span>{v.proof}</span><small>Workflow and evidence detail continues on the industry page.</small></div></div></article>)}</div></section>}

function Economics(){return <section className="economics-proof"><div className="economics-card cost-card" data-agency-reveal><p>MODELED ECONOMICS</p><h2>Up to 60% lower modeled total cost.<br/><em>And the assets remain under your control.</em></h2><div className="cost-graph" role="img" aria-label="Illustrative comparison of per-seat rented AI cost rising with adoption versus a flatter enterprise license"><span className="axis-y">COST / USER</span><span className="axis-x">ADOPTION →</span><i className="rent-line"/><i className="own-line"/><b className="rent-label">RENTED AI · PER SEAT + TOKEN</b><b className="own-label">CORPORATE GPT · FLAT LICENSE</b></div><p className="economics-copy">Illustrative Neurologic AI model, 2026. Customer-specific assumptions are shared in writing during the briefing.</p></div><div className="economics-card learn-card" data-agency-reveal><p>ILLUSTRATIVE LEARNING CURVE</p><h2>Improvement is reviewed every quarter. <em>On your evaluation set.</em></h2><div className="quarter-bars" role="img" aria-label="Illustrative quarterly improvement bars from baseline through quarter four"><div><i style={{height:"34%"}}/><span>Q1</span></div><div><i style={{height:"51%"}}/><span>Q2</span></div><div><i style={{height:"72%"}}/><span>Q3</span></div><div><i style={{height:"92%"}}/><span>Q4</span><b>ILLUSTRATIVE</b></div></div><p className="economics-copy">Accuracy, retrieval success, acceptance, and time-to-output are measured on the customer’s agreed tasks; no generic uplift is promised.</p></div></section>}

export function TeamSection({full=false}:{full?:boolean}){return <section className={`agency-team ${full?"full":""}`}><div className="team-intro" data-agency-reveal><p>WHO BUILDS IT</p><h2>Leadership that has<br/>done this <em>before.</em></h2><div><strong>03</strong><span>senior leaders across AI, architecture, and operations</span></div><small>Supported by a multidisciplinary delivery team spanning data science, AI engineering, software engineering, MLOps, and deployment.</small></div><div className="leader-grid">{leaders.map(l=><article key={l.name} data-agency-reveal><span>{l.initials}</span><div><small>{l.role}</small><h3>{l.name}</h3><p>{l.bio}</p><b>{l.proof}</b></div></article>)}</div>{full&&<div className="engineering-bench"><h3>One engineering organisation. Five disciplines.</h3>{["Foundation models & retrieval","Agent systems & workflows","Enterprise platform engineering","MLOps, security & deployment","Industry data science"].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b></div>)}</div>}</section>}

function DeploymentRail(){return <section className="deployment-rail"><div className="agency-section-head" data-agency-reveal><div><p>THE REFERENCE PATH</p><h2>A reported <em>12-week rollout shape.</em></h2></div><span>The actual plan depends on security review, infrastructure readiness, connectors, validation, and the agreed production scope.</span></div><div className="deployment-track" data-agency-reveal data-mobile-track role="region" aria-label="Reference rollout phases" tabIndex={0}><article><span>REFERENCE · WEEKS 1–3</span><h3>Establish the boundary</h3><p>Confirm infrastructure, approved data paths, identity, connectors, operating roles, and pilot readiness.</p></article><article><span>REFERENCE · WEEKS 4–8</span><h3>Test real work</h3><p>Build the first workflows on approved data and establish the customer evaluation and evidence set.</p></article><article><span>REFERENCE · WEEKS 9–12</span><h3>Review production readiness</h3><p>Evaluate controls, outcomes, ownership, support, and rollout criteria before any broader release.</p></article></div></section>}

function AgencyCTA(){return <section className="agency-cta"><p>A 45-MINUTE WORKING SESSION</p><h2>Shape the first deployment hypothesis.<br/><em>Then test it.</em></h2><div><span>Your top three use cases</span><span>The first systems to connect</span><span>Evidence your reviewers will expect</span></div><Link href="/briefing">Request a sovereignty briefing ↗</Link></section>}

export function AgencyHome(){return <div className="agency-site"><AgencyMotion/><SiteHeader/><main id="main"><AgencyHero/><ClientProof/><ArchitectureStory/><ProductHorizontal/><CorporateLLM/><AgentFlow/><VerticalProof/><Economics/><TeamSection/><DeploymentRail/><AgencyCTA/></main><SiteFooter/></div>}

export function AgencyProofPage(){return <div className="agency-site"><AgencyMotion/><SiteHeader/><main id="main"><section className="agency-page-hero"><p>CUSTOMERS & PROOF</p><h1>Production evidence.<br/><em>Not testimonial theatre.</em></h1><span>Three regulated wedges. Named deployments. Measured outcomes. Every claim is expected to survive your security, procurement, and executive reviews.</span></section><ClientProof expanded/><section className="proof-standards"><div><p>THE PROOF STANDARD</p><h2>Every deployment gets <em>a scorecard.</em></h2></div>{[["Search success","35% → 85%"],["Time-to-answer","−80%"],["Compliance review","−75%"],["Audit preparation","−50%"],["Shadow AI","−95%"]].map(x=><article key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></article>)}</section><VerticalProof full/><AgencyCTA/></main><SiteFooter/></div>}

export function AgencyCompanyPage(){return <div className="agency-site"><AgencyMotion/><SiteHeader/><main id="main"><section className="agency-page-hero company-hero"><p>NEUROLOGIC AI</p><h1>The team building AI<br/>enterprises are <em>allowed to own.</em></h1><span>Corporate GPT combines enterprise infrastructure, foundation-model research, regulated-industry depth, and the operating discipline to ship inside the customer perimeter.</span></section><TeamSection full/><section className="company-belief"><p>THE BELIEF</p><h2>Intelligence about your company should <em>belong to your company.</em></h2><span>Every enterprise is about to run on AI. The question is whether that intelligence accumulates inside the enterprise—as an asset it owns—or inside a vendor, as a service it rents. We build for the first outcome.</span><div><article><strong>27+</strong><p>production AI projects and products delivered by the founder</p></article><article><strong>2</strong><p>US patents held across the leadership team</p></article><article><strong>5</strong><p>delivery disciplines across AI and engineering</p></article><article><strong>3</strong><p>regulated sectors represented across named evidence</p></article></div></section><AgencyCTA/></main><SiteFooter/></div>}

export function AgencyIndustriesPage(){return <div className="agency-site"><AgencyMotion/><SiteHeader/><main id="main"><section className="agency-page-hero"><p>INDUSTRIES</p><h1>One sovereign platform.<br/><em>Your industry&apos;s operating shape.</em></h1><span>Not vertical wallpaper. Each industry motion starts from a different data boundary, workflow, approval chain, and measurable outcome.</span></section><VerticalProof full/><section className="industry-secondary"><p>ADDITIONAL SOLUTION PACKS</p><div><Link href="/industries/manufacturing"><span>04</span><h3>Manufacturing & industrial</h3><p>Tribal knowledge, maintenance intelligence, BOM workflows, supplier quality, and multilingual floor support.</p><b>Explore ↗</b></Link><Link href="/industries/retail"><span>05</span><h3>Retail & hospitality</h3><p>Product expertise, inventory-aware concierge, merchandising intelligence, and policy support for every shift.</p><b>Explore ↗</b></Link></div></section><AgencyCTA/></main><SiteFooter/></div>}

export function AgencyGovernmentPage(){return <div className="agency-site"><AgencyMotion/><SiteHeader/><main id="main"><section className="agency-page-hero government-hero"><p>GOVERNMENT & PUBLIC SECTOR</p><h1>Public answers that can be <em>defended line by line.</em></h1><span>Ground citizen and founder guidance exclusively in official documents. Deploy in-region or inside government infrastructure. Preserve the audit trail from question to cited source.</span></section><section className="government-proof"><div><span>LIVE PROOF</span><h2>Dubai CommerCity</h2><p>A UAE government free zone serving founders on its public website, 24/7, with every answer grounded in official regulations.</p></div><strong>24/7<small>grounded public guidance</small></strong></section><section className="government-workflows">{[["Official-information Q&A","Every sentence links to the regulation or policy passage that supports it."],["Founder & investor advisory","Guide businesses through programs, requirements, and next actions."],["Program navigation","Map eligibility and application steps without inventing policy."],["In-region sovereignty","Data, models, indexes, and telemetry remain inside the required boundary."]].map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</section><AgencyCTA/></main><SiteFooter/></div>}
