"use client";

import { useEffect } from "react";
import { NativeLink as Link } from "./native-link";
import { SiteFooter, SiteHeader } from "./site";

const clients=[
  {name:"Globus Medical",tag:"NYSE-LISTED MEDICAL DEVICES",summary:"5,000 users, fully on-prem. Every data point traced to source; human review intact. Zero token-cost overhead.",metric:"4–5×",metricLabel:"faster research reviews",facts:["5,000 users","Fully on-prem","Healthcare"]},
  {name:"Micron",tag:"SEMICONDUCTOR",summary:"A full engineering loop—simulate, review, revise, re-run—now executes autonomously. Engineers moved to design work.",metric:"100%",metricLabel:"autonomous execution",facts:["Paid proof of concept","Agent workflows","Semiconductor"]},
  {name:"Dubai CommerCity",tag:"UAE GOVERNMENT FREE ZONE",summary:"Founders served on the public website, with every answer grounded in official regulations and available around the clock.",metric:"24/7",metricLabel:"on the public site",facts:["Public-facing AI","Official sources","UAE"]}
];

const products=[
  {n:"01",eyebrow:"ENTERPRISE SEARCH · AUTO MODE",title:"Just ask, in plain English.",body:"No folders to dig through. Auto Mode routes each question across your company knowledge, then returns a sourced answer in seconds.",stat:"3.3s",statLabel:"to a sourced answer",image:"/product/enterprise-search.png",href:"/platform/know"},
  {n:"02",eyebrow:"ENTERPRISE SEARCH · DATABASE MODE",title:"From a question to a chart.",body:"Describe the number you need. The agent writes SQL, queries your live database, visualises the result, and exports it—without an analyst in the loop.",stat:"Live",statLabel:"PostgreSQL",image:"/product/database-mode.png",href:"/platform/know"},
  {n:"03",eyebrow:"AGENT BUILDER",title:"Agents that take action.",body:"Connect backend systems, SaaS tools, and specialist agents in a visual workflow. Human approvals stay exactly where the business requires them.",stat:"100%",statLabel:"governed execution",image:"/product/agent-builder.png",href:"/platform/build"},
  {n:"04",eyebrow:"AI WORKSPACE",title:"One place for every agent.",body:"Your agents, multi-agent workflows, and ready-to-use platform agents—published, governed, and available across the enterprise.",stat:"3",statLabel:"capability bands",image:"/product/ai-workspace.png",href:"/platform/work"}
];

const verticals=[
  {n:"01",name:"Healthcare & medical devices",proof:"5,000 users · fully on-prem · production",headline:"Compliance first. Intelligence second. Both by design.",body:"Surgical case preparation, regulatory intelligence, CAPA support, and clinical enablement—grounded in controlled documents, permissioned by role, and fully auditable.",workflows:["Surgical case preparation","Regulatory intelligence","Quality & CAPA","Clinical enablement"],metric:"4–5×",metricLabel:"faster research reviews",href:"/industries/healthcare"},
  {n:"02",name:"Semiconductor",proof:"Autonomous engineering loop · paid POC",headline:"Where IP is the company, sovereignty is the product.",body:"Design and process knowledge never crosses the boundary. Agent workflows simulate, review, revise, and re-run while engineers stay focused on design decisions.",workflows:["Design-doc navigation","Process knowledge","Engineering review","Multi-agent simulation"],metric:"100%",metricLabel:"autonomous execution",href:"/industries/semiconductor"},
  {n:"03",name:"Government & public sector",proof:"Public website · official regulations · UAE",headline:"Public answers that can be defended line by line.",body:"Citizen and founder guidance grounded only in official regulations, available 24/7, deployed in-region, and structured for the audit and language requirements of public institutions.",workflows:["Official-information Q&A","Founder advisory","Program navigation","Regulatory guidance"],metric:"24/7",metricLabel:"grounded public service",href:"/industries/government"}
];

const leaders=[
  {initials:"SD",name:"Dr. Santanu Das",role:"Chairman",bio:"Founded and led TranSwitch Corporation from inception to a NASDAQ listing. Brings semiconductor, systems, and public-company operating depth to the sovereign AI thesis.",proof:"NASDAQ FOUNDER · SEMICONDUCTOR"},
  {initials:"NA",name:"Nishan Ali",role:"Chief Executive Officer",bio:"M.Tech in AI; formerly UnitedHealth Group. Nine years in core data science, 27+ production projects, two US patents, and the founder leading every first customer briefing.",proof:"AI · HEALTHCARE · ENTERPRISE"},
  {initials:"JG",name:"John Gillotte",role:"Chief Technology Officer",bio:"Twenty-two years building enterprise infrastructure and AI systems, including founding-engineering experience at AWS and healthcare foundation models tested on public benchmarks.",proof:"AWS · FOUNDATION MODELS · 22 YEARS"},
  {initials:"AA",name:"Alfaz Ahmed",role:"Engineering Lead",bio:"Formerly Amazon and Siemens. Leads the engineering organisation across the United States and India, turning platform research into deployed enterprise capability.",proof:"AMAZON · SIEMENS · DELIVERY"}
];

const clamp=(v:number)=>Math.max(0,Math.min(1,v));
function AgencyMotion(){useEffect(()=>{const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const reveals=[...document.querySelectorAll<HTMLElement>("[data-agency-reveal]")];const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){(e.target as HTMLElement).classList.add("is-in");io.unobserve(e.target)}}),{threshold:.12,rootMargin:"0px 0px -40px"});reveals.forEach(x=>io.observe(x));const horizontals=[...document.querySelectorAll<HTMLElement>("[data-agency-horizontal]")];const architectures=[...document.querySelectorAll<HTMLElement>("[data-agency-architecture]")];let raf=0,dirty=true;const frame=()=>{if(dirty){dirty=false;horizontals.forEach(section=>{const r=section.getBoundingClientRect(),p=clamp(-r.top/Math.max(1,r.height-innerHeight)),stage=section.querySelector<HTMLElement>("[data-agency-stage]")!,track=section.querySelector<HTMLElement>("[data-agency-track]")!;if(!stage||!track)return;const max=Math.max(0,track.scrollWidth-stage.clientWidth);track.style.transform=innerWidth<800||reduced?"none":`translate3d(${-p*max}px,0,0)`;section.style.setProperty("--agency-p",String(p))});architectures.forEach(section=>{const r=section.getBoundingClientRect(),p=clamp((innerHeight*.65-r.top)/Math.max(1,r.height+innerHeight*.3));section.style.setProperty("--arch-p",String(reduced?1:p))})}raf=requestAnimationFrame(frame)};const mark=()=>{dirty=true};addEventListener("scroll",mark,{passive:true});addEventListener("resize",mark,{passive:true});raf=requestAnimationFrame(frame);return()=>{cancelAnimationFrame(raf);removeEventListener("scroll",mark);removeEventListener("resize",mark);io.disconnect()}},[]);return null}

function AgencyHero(){return <section className="agency-hero"><div className="agency-hero-copy"><p>CORPORATE GPT · SOVEREIGN ENTERPRISE AI</p><h1>AI inside your walls.<br/>Under <em>your control.</em></h1><span>ChatGPT-class enterprise AI and custom agents, deployed entirely inside your data centre or cloud tenant—so your documents, data, and learned intelligence never leave.</span><div className="agency-actions"><Link href="/briefing">Scope your deployment</Link><Link href="/platform">Explore the platform ↗</Link></div><div className="agency-hero-stats"><b>03 <span>regulated industries live</span></b><b>12 <span>weeks to production</span></b><b>−60% <span>modeled total cost</span></b></div></div><div className="sovereign-object" aria-label="Corporate GPT runs as a closed sovereign stack inside the organisation boundary"><div className="object-boundary"><span>YOUR ORGANISATION&apos;S BOUNDARY</span><div className="object-ring ring-a"><i>EMPLOYEES</i></div><div className="object-ring ring-b"><i>AI AGENTS</i></div><div className="object-ring ring-c"><i>CORPORATE LLM</i></div><div className="object-core"><img src="/brand/neurologic-logogram-white.png" alt=""/><b>CORPORATE GPT</b><small>ZERO EGRESS</small></div><p>NOTHING CROSSES THE LINE</p></div></div></section>}

export function ClientProof({expanded=false}:{expanded?:boolean}){return <section className={`client-proof ${expanded?"expanded":""}`}><div className="agency-section-head" data-agency-reveal><div><p>WHO RUNS IT TODAY</p><h2>Proven where the reviews <em>are hardest.</em></h2></div><span>Medical devices. Semiconductors. Government.<br/>If it clears their reviews, it clears yours.</span></div><div className="client-case-grid">{clients.map((c,i)=><article key={c.name} data-agency-reveal><div className="client-case-top"><span>0{i+1}</span><small>{c.tag}</small></div><h3>{c.name}</h3><p>{c.summary}</p><div className="client-metric"><strong>{c.metric}</strong><span>{c.metricLabel}</span></div><div className="client-facts">{c.facts.map(x=><b key={x}>{x}</b>)}</div>{expanded&&<Link href="/briefing">Discuss this deployment ↗</Link>}</article>)}</div></section>}

function ArchitectureStory(){const layers=[{name:"AI applications",desc:"Employee-facing apps & workflows",owner:"YOU BUILD"},{name:"AI agents",desc:"Composed, governed, orchestrated",owner:"WE BUILD · YOU BUILD"},{name:"Corporate LLM",desc:"Patented model IP + your knowledge",owner:"WE PROVIDE & BUILD"},{name:"GPU servers",desc:"Accelerated inference and learning",owner:"YOU OWN · WE RESELL"},{name:"Data centre / cloud",desc:"On-premise or your tenant",owner:"YOU OWN"}];return <section className="architecture-story" data-agency-architecture><div className="architecture-copy" data-agency-reveal><p>SOVEREIGN AI ARCHITECTURE</p><h2>The whole stack—<em>yours or ours.</em></h2><span>You own the infrastructure and intelligence. We provide the patented model and platform. Your teams build applications and agents on top—or we build with you.</span><Link href="/deployment">Explore deployment architecture ↗</Link></div><div className="architecture-stack">{layers.map((x,i)=><div className={`arch-layer arch-${i}`} key={x.name} style={{"--layer":i} as React.CSSProperties}><span>0{i+1}</span><div><h3>{x.name}</h3><p>{x.desc}</p></div><b>{x.owner}</b></div>)}<small>YOUR SECURITY BOUNDARY</small></div></section>}

function ProductHorizontal(){return <section className="agency-horizontal" data-agency-horizontal><div className="agency-horizontal-stage" data-agency-stage><div className="product-story-head"><p>THE PRODUCT · REAL INTERFACES</p><h2>From a question to <em>an outcome.</em></h2><span>Scroll through the product</span></div><div className="agency-product-track" data-agency-track>{products.map(p=><article key={p.n}><div className="product-panel-copy"><span>{p.n} / 04</span><small>{p.eyebrow}</small><h3>{p.title}</h3><p>{p.body}</p><div><strong>{p.stat}</strong><em>{p.statLabel}</em></div><Link href={p.href}>Explore this capability ↗</Link></div><div className="product-shot"><img src={p.image} alt={`${p.title} Corporate GPT product interface`}/></div></article>)}</div><div className="agency-horizontal-progress"><i/></div></div></section>}

function CorporateLLM(){return <section className="corporate-llm"><div className="agency-section-head" data-agency-reveal><div><p>YOUR OWN CORPORATE LLM</p><h2>Not a rented model.<br/><em>Your corporate intelligence.</em></h2></div><span>It learns your vocabulary, precedents, and ways of working. The model is your asset—not a rental.</span></div><div className="llm-equation" data-agency-reveal><div><span>01</span><h3>Open foundation model</h3><p>Strong open weights as the base.</p></div><b>+</b><div><span>02</span><h3>Patented model IP</h3><p>Enterprise-grade behaviour and grounding.</p></div><b>+</b><div><span>03</span><h3>Your knowledge</h3><p>Your language, policies, documents, and decisions.</p></div><b>=</b><div className="owned"><span>04</span><h3>Owned by you</h3><p>A corporate LLM unique to your organisation.</p></div></div></section>}

function AgentFlow(){return <section className="agent-flow"><div className="agency-section-head" data-agency-reveal><div><p>AGENTS THAT TAKE ACTION</p><h2>From workflows to outcomes—<em>with you in control.</em></h2></div><span>Not a rogue agent. A diligent digital colleague that asks permission when the work matters.</span></div><div className="flow-rail" data-agency-reveal><div><span>01</span><i>↯</i><h3>Trigger</h3><p>From ERP, CRM, service desk, or schedule.</p></div><b>→</b><div><span>02</span><i>◎</i><h3>Multi-step work</h3><p>Specialist agents coordinate tools and systems.</p></div><b>→</b><div className="approval"><span>03</span><i>✓</i><h3>Approval gate</h3><p>Human sign-off where policy requires it.</p></div><b>→</b><div><span>04</span><i>◆</i><h3>Done</h3><p>Outcome delivered, logged, and attributable.</p></div></div></section>}

export function VerticalProof({full=false}:{full?:boolean}){return <section className={`vertical-proof ${full?"full":""}`}><div className="agency-section-head" data-agency-reveal><div><p>VERTICAL DEPTH</p><h2>Built where generic AI <em>cannot operate.</em></h2></div><span>Three regulated industries live. Each with a distinct workflow, risk model, and proof standard.</span></div><div className="vertical-list">{verticals.map(v=><article key={v.name} data-agency-reveal><div className="vertical-number">{v.n}</div><div className="vertical-main"><small>{v.proof}</small><h3>{v.name}</h3><h4>{v.headline}</h4><p>{v.body}</p><div>{v.workflows.map(x=><span key={x}>{x}</span>)}</div><Link href={v.href}>Explore the vertical ↗</Link></div><div className="vertical-metric"><strong>{v.metric}</strong><span>{v.metricLabel}</span><div className="vertical-radar"><i/><i/><i/><b>{v.name.split(" ")[0].toUpperCase()}</b></div></div></article>)}</div></section>}

function Economics(){return <section className="economics-proof"><div className="economics-card cost-card" data-agency-reveal><p>THE ECONOMICS</p><h2>60% lower total cost.<br/><em>And it becomes an asset.</em></h2><div className="cost-graph"><span className="axis-y">COST / USER</span><span className="axis-x">ADOPTION →</span><i className="rent-line"/><i className="own-line"/><b className="rent-label">RENTED AI · PER SEAT + TOKEN</b><b className="own-label">CORPORATE GPT · FLAT LICENSE</b></div></div><div className="economics-card learn-card" data-agency-reveal><p>THE COMPOUNDING ASSET</p><h2>It gets smarter every quarter. <em>Provably.</em></h2><div className="quarter-bars"><div><i style={{height:"34%"}}/><span>Q1</span></div><div><i style={{height:"51%"}}/><span>Q2</span></div><div><i style={{height:"72%"}}/><span>Q3</span></div><div><i style={{height:"92%"}}/><span>Q4</span><b>+14%</b></div></div><p className="economics-copy">Reviewed with you on a dashboard: accuracy, retrieval success, acceptance, and time-to-output.</p></div></section>}

export function TeamSection({full=false}:{full?:boolean}){return <section className={`agency-team ${full?"full":""}`}><div className="team-intro" data-agency-reveal><p>WHO BUILDS IT</p><h2>A team that has<br/>done this <em>before.</em></h2><div><strong>30</strong><span>AI engineers across the United States and India</span></div><small>Foundation-model work tested against flagship public healthcare benchmarks. Enterprise operators from healthcare, cloud infrastructure, industrial engineering, and semiconductor.</small></div><div className="leader-grid">{leaders.map(l=><article key={l.name} data-agency-reveal><span>{l.initials}</span><div><small>{l.role}</small><h3>{l.name}</h3><p>{l.bio}</p><b>{l.proof}</b></div></article>)}</div>{full&&<div className="engineering-bench"><h3>One engineering organisation. Five disciplines.</h3>{["Foundation models & retrieval","Agent systems & workflows","Enterprise platform engineering","MLOps, security & deployment","Industry data science"].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b></div>)}</div>}</section>}

function DeploymentRail(){return <section className="deployment-rail"><div className="agency-section-head" data-agency-reveal><div><p>THE PATH</p><h2>Live in <em>12 weeks.</em></h2></div><span>Then a quarterly rhythm: refresh, optimise, and review measured improvement together.</span></div><div className="deployment-track" data-agency-reveal><article><span>WEEKS 1–3</span><h3>On your infrastructure</h3><p>Deployed inside your perimeter, connected, permission-aware, and ready for pilot users.</p></article><article><span>WEEKS 4–8</span><h3>Real work begins</h3><p>Skills built on your data. Pilot teams produce referenced work and the first evaluation set.</p></article><article><span>WEEKS 9–12</span><h3>Department scale</h3><p>Rolled across departments. Your admins take the keys and the first ROI readout is reviewed.</p></article></div></section>}

function AgencyCTA(){return <section className="agency-cta"><p>ONE WORKING SESSION IS ENOUGH TO SCOPE IT</p><h2>Stop renting generic intelligence.<br/><em>Grow your own.</em></h2><div><span>Your top three use cases</span><span>The first five systems to connect</span><span>Metrics your CFO will accept</span></div><Link href="/briefing">Scope your sovereign deployment ↗</Link></section>}

export function AgencyHome(){return <div className="agency-site"><AgencyMotion/><SiteHeader/><main id="main"><AgencyHero/><ClientProof/><ArchitectureStory/><ProductHorizontal/><CorporateLLM/><AgentFlow/><VerticalProof/><Economics/><TeamSection/><DeploymentRail/><AgencyCTA/></main><SiteFooter/></div>}

export function AgencyProofPage(){return <div className="agency-site"><AgencyMotion/><SiteHeader/><main id="main"><section className="agency-page-hero"><p>CUSTOMERS & PROOF</p><h1>Production evidence.<br/><em>Not testimonial theatre.</em></h1><span>Three regulated wedges. Named deployments. Measured outcomes. Every claim is expected to survive your security, procurement, and executive reviews.</span></section><ClientProof expanded/><section className="proof-standards"><div><p>THE PROOF STANDARD</p><h2>Every deployment gets <em>a scorecard.</em></h2></div>{[["Search success","35% → 85%"],["Time-to-answer","−80%"],["Compliance review","−75%"],["Audit preparation","−50%"],["Shadow AI","−95%"]].map(x=><article key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></article>)}</section><VerticalProof full/><AgencyCTA/></main><SiteFooter/></div>}

export function AgencyCompanyPage(){return <div className="agency-site"><AgencyMotion/><SiteHeader/><main id="main"><section className="agency-page-hero company-hero"><p>NEUROLOGIC AI</p><h1>The team building AI<br/>enterprises are <em>allowed to own.</em></h1><span>Corporate GPT combines enterprise infrastructure, foundation-model research, regulated-industry depth, and the operating discipline to ship inside the customer perimeter.</span></section><TeamSection full/><section className="company-belief"><p>THE BELIEF</p><h2>Intelligence about your company should <em>belong to your company.</em></h2><span>Every enterprise is about to run on AI. The question is whether that intelligence accumulates inside the enterprise—as an asset it owns—or inside a vendor, as a service it rents. We build for the first outcome.</span><div><article><strong>27+</strong><p>production AI projects and products delivered by the founder</p></article><article><strong>2</strong><p>US patents held across the leadership team</p></article><article><strong>30</strong><p>engineers across the United States and India</p></article><article><strong>3</strong><p>regulated industries represented in live deployments</p></article></div></section><AgencyCTA/></main><SiteFooter/></div>}

export function AgencyIndustriesPage(){return <div className="agency-site"><AgencyMotion/><SiteHeader/><main id="main"><section className="agency-page-hero"><p>INDUSTRIES</p><h1>One sovereign platform.<br/><em>Your industry&apos;s operating shape.</em></h1><span>Not vertical wallpaper. Each industry motion starts from a different data boundary, workflow, approval chain, and measurable outcome.</span></section><VerticalProof full/><section className="industry-secondary"><p>ADDITIONAL SOLUTION PACKS</p><div><Link href="/industries/manufacturing"><span>04</span><h3>Manufacturing & industrial</h3><p>Tribal knowledge, maintenance intelligence, BOM workflows, supplier quality, and multilingual floor support.</p><b>Explore ↗</b></Link><Link href="/industries/retail"><span>05</span><h3>Retail & hospitality</h3><p>Product expertise, inventory-aware concierge, merchandising intelligence, and policy support for every shift.</p><b>Explore ↗</b></Link></div></section><AgencyCTA/></main><SiteFooter/></div>}

export function AgencyGovernmentPage(){return <div className="agency-site"><AgencyMotion/><SiteHeader/><main id="main"><section className="agency-page-hero government-hero"><p>GOVERNMENT & PUBLIC SECTOR</p><h1>Public answers that can be <em>defended line by line.</em></h1><span>Ground citizen and founder guidance exclusively in official documents. Deploy in-region or inside government infrastructure. Preserve the audit trail from question to cited source.</span></section><section className="government-proof"><div><span>LIVE PROOF</span><h2>Dubai CommerCity</h2><p>A UAE government free zone serving founders on its public website, 24/7, with every answer grounded in official regulations.</p></div><strong>24/7<small>grounded public guidance</small></strong></section><section className="government-workflows">{[["Official-information Q&A","Every sentence links to the regulation or policy passage that supports it."],["Founder & investor advisory","Guide businesses through programs, requirements, and next actions."],["Program navigation","Map eligibility and application steps without inventing policy."],["In-region sovereignty","Data, models, indexes, and telemetry remain inside the required boundary."]].map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</section><AgencyCTA/></main><SiteFooter/></div>}
