"use client";

import { NativeLink as Link } from "./native-link";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import type { FormEvent } from "react";
import type { PageContent, ContentBlock } from "../content";
import { CurveModule, LoopDiagram, Reveal, SiteFooter, SiteHeader } from "./site";

const clampFilm=(v:number)=>Math.max(0,Math.min(1,v));
const smoothFilm=(a:number,b:number,x:number)=>{const t=clampFilm((x-a)/(b-a||1));return t*t*(3-2*t)};
function InnerMotionRuntime(){useEffect(()=>{const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const films=[...document.querySelectorAll<HTMLElement>("[data-inner-film]")];let raf=0,dirty=true;const update=()=>{if(dirty){dirty=false;films.forEach(section=>{const r=section.getBoundingClientRect(),p=clampFilm(-r.top/Math.max(1,r.height-innerHeight));section.style.setProperty("--inner-p",String(p));section.querySelectorAll<HTMLElement>("[data-inner-range]").forEach(el=>{const [a,b]=el.dataset.innerRange!.split(",").map(Number);const vis=Math.min(smoothFilm(a,a+.07,p),1-smoothFilm(b-.07,b,p));el.style.opacity=String(reduced?1:vis);el.style.transform=reduced?"none":`translateY(${(1-vis)*20}px)`})})}raf=requestAnimationFrame(update)};const onScroll=()=>{dirty=true};addEventListener("scroll",onScroll,{passive:true});addEventListener("resize",onScroll,{passive:true});raf=requestAnimationFrame(update);return()=>{cancelAnimationFrame(raf);removeEventListener("scroll",onScroll);removeEventListener("resize",onScroll)}},[]);return null}

function BlockVisual({ type }: { type?: ContentBlock["visual"] }) {
  if (type === "curve") return <div className="inner-visual"><CurveModule /></div>;
  if (type === "loop") return <div className="inner-visual"><LoopDiagram /></div>;
  if (type === "pillars") return <div className="system-flow" aria-label="KNOW to WORK to LEARN to BUILD, governed by TRUST"><span>KNOW</span><i>→</i><span>WORK</span><i>→</i><span className="core">LEARN</span><i>→</i><span>BUILD</span><b>TRUST · GOVERNANCE ACROSS EVERY STEP</b></div>;
  if (type === "gates") return <div className="gate-visual">{["INFOSEC","PRIVACY","COMPLIANCE","PROCUREMENT"].map((x,i)=><div key={x}><span>GATE 0{i+1}</span><b>{x}</b><em>PASS</em></div>)}</div>;
  if (type === "tiers") return <div className="tier-visual">{[["S","50–100"],["M","100–500"],["L","500–2,000"],["XL","2,000–5,000"]].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]} USERS</span></div>)}</div>;
  if (type === "timeline") return null;
  return null;
}

function SignatureGraphic({page}:{page:PageContent}){const kind=page.blocks.find(x=>x.visual)?.visual;return <div className={`signature-graphic signature-${kind||"system"}`} aria-hidden="true"><div className="signature-perimeter"><span>YOUR PERIMETER</span><div className="signature-core">{kind==="curve"?"+14%":kind==="gates"?"PASS":kind==="timeline"?"12 WKS":page.label?.includes("PILLAR")?page.label.split("—")[0].replace("PILLAR","").trim():"AEI"}</div>{["KNOW","WORK","LEARN","BUILD","TRUST"].map((x,i)=><i key={x} style={{"--s":i} as React.CSSProperties}>{x}</i>)}</div></div>}

function SignatureFilm({page}:{page:PageContent}){const beats=page.blocks.slice(0,3);if(page.accent==="paper"||page.label?.includes("Legal"))return null;return <section className="inner-film" data-inner-film><div className="inner-film-stage"><div className="inner-film-copy">{beats.map((b,i)=><div key={b.title} data-inner-range={`${i*.33+.02},${i*.33+.31}`}><span>{b.label||`CHAPTER 0${i+1}`}</span><h2>{b.title}</h2><p>{b.body||b.items?.[0]?.body}</p></div>)}</div><SignatureGraphic page={page}/><div className="inner-film-progress"><i/></div><small>SCROLL TO MOVE THROUGH THE SYSTEM</small></div></section>}

function ProductEvidence({page}:{page:PageContent}) {
  const key=page.label?.includes("PILLAR 01")?"know":page.label?.includes("PILLAR 02")?"work":page.label?.includes("PILLAR 04")?"build":null;
  if(!key)return null;
  const evidence={
    know:{eyebrow:"PRODUCT INTERFACE · ENTERPRISE SEARCH",title:"A real answer. With the real sources attached.",copy:"Grounded-answer mode routes a plain-English question across permissioned enterprise knowledge. Database Mode prepares an approved query, then returns the chart and export.",image:"/product/enterprise-search.webp",width:2200,height:1365},
    work:{eyebrow:"PRODUCT INTERFACE · AI WORKSPACE",title:"Every agent, workflow, and outcome in one governed workspace.",copy:"Publish approved specialist agents, compose multi-agent workflows, and give teams one place to move from a question to finished work.",image:"/product/ai-workspace.webp",width:2200,height:1816},
    build:{eyebrow:"PRODUCT INTERFACE · AGENT BUILDER",title:"The workflow is visual. The controls are explicit.",copy:"Connect approved systems and specialist agents, define each step, and place approval gates exactly where enterprise policy requires them.",image:"/product/agent-builder.webp",width:2200,height:1323}
  }[key];
  return <section className="inner-product-evidence"><div><span>{evidence.eyebrow}</span><h2>{evidence.title}</h2><p>{evidence.copy}</p></div><figure><Image src={evidence.image} alt={`${page.label} product interface`} width={evidence.width} height={evidence.height} sizes="(max-width: 760px) calc(100vw - 40px), 58vw"/></figure></section>
}

function ContentSection({ block, index }: { block: ContentBlock; index: number }) {
  const isPaper = index % 3 === 1;
  return <Reveal className={`inner-section ${isPaper ? "paper-section" : ""}`}><div className="container"><div className="inner-section-head"><div><p className={`eyebrow ${isPaper ? "ink" : block.visual === "curve" ? "proof" : ""}`}>{block.label}</p><h2 className={`section-title ${isPaper ? "ink" : ""}`}>{block.title}</h2></div>{block.body && <p className={`lead ${isPaper ? "ink-muted" : ""}`}>{block.body}</p>}</div><BlockVisual type={block.visual}/>{block.items && block.visual !== "timeline" && <div className={`detail-grid ${block.items.length === 5 ? "five" : ""}`}>{block.items.map((item,i)=><article key={item.title}><span className="detail-index">{String(i+1).padStart(2,"0")}</span><h3>{item.title}</h3><p>{item.body}</p>{item.metric&&<em>{item.metric}</em>}</article>)}</div>}{block.visual === "timeline" && block.items && <div className="timeline-rail">{block.items.map((item,i)=><div key={item.title}><span>{String(i+1).padStart(2,"0")}</span><h3>{item.title}</h3><p>{item.body}</p></div>)}</div>}{block.note&&<p className="mono-note">{block.note}</p>}</div></Reveal>;
}

export function InnerPage({ page }: { page: PageContent }) { return <div className={`site-shell inner-page cinematic-inner ${page.accent === "proof" ? "proof-page" : ""}`}><InnerMotionRuntime/><SiteHeader/><main id="main"><section className={`inner-hero ${page.accent === "paper" ? "paper-hero" : ""}`}><div className="inner-orbit"/><div className="container inner-perimeter"><div><p className={`eyebrow ${page.accent === "paper" ? "ink" : page.accent === "proof" ? "proof" : ""}`}>{page.label}</p><h1>{page.hero}</h1><p>{page.intro}</p><Link href="/briefing" className="pill-button">Book a briefing</Link></div><div className="hero-coordinate" aria-hidden="true"><span>01</span><span>02</span><span>03</span><i/></div></div></section>{page.stats&&<section className="inner-stats"><div className="container">{page.stats.map(x=><div key={x.value}><strong>{x.value}</strong><span>{x.label}</span></div>)}</div></section>}<ProductEvidence page={page}/><SignatureFilm page={page}/>{page.blocks.map((block,i)=><ContentSection block={block} index={i} key={block.title}/>) }<section className="cinema-cta inner-final"><p>The next move</p><h2>{page.cta}</h2>{page.ctaBody&&<span>{page.ctaBody}</span>}<Link href="/briefing" className="pill-button">Book a briefing</Link></section></main><SiteFooter/></div> }

export function BriefingPage() {
  const startedAt=useRef(0);
  const [status,setStatus]=useState<"idle"|"sending"|"success"|"error">("idle");
  const [fallbackHref,setFallbackHref]=useState("mailto:nishan@neurologicai.com?subject=Corporate%20GPT%20executive%20briefing");
  useEffect(()=>{startedAt.current=Date.now()},[]);
  const submitRequest=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;const values=Object.fromEntries(new FormData(form).entries());const subject=`Corporate GPT executive briefing — ${values.company||"organisation"}`;const body=[`Name: ${values.name||""}`,`Work email: ${values.email||""}`,`Company: ${values.company||""}`,"",`Anything we should know?:\n${values.comments||"—"}`].join("\n");setFallbackHref(`mailto:nishan@neurologicai.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`);setStatus("sending");try{const response=await fetch("/api/briefing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...values,startedAt:startedAt.current})});if(!response.ok)throw new Error("Submission unavailable");form.reset();setStatus("success")}catch{setStatus("error")}};
  return <div className="world-page briefing-world"><SiteHeader/><main id="main"><section className="briefing-world-hero"><div><p>EXECUTIVE BRIEFING · 45 MINUTES</p><h1>Bring one hard workflow.<br/><em>Leave with a clear path forward.</em></h1><span>We will identify where Corporate GPT can create the most value, the boundary it should operate within, and the fastest credible first step.</span></div><aside><span>IN 45 MINUTES</span>{["Focus the highest-value starting point","Map the systems and operating boundary","Agree a practical next step"].map((x,i)=><b key={x}>{String(i+1).padStart(2,"0")} · {x}</b>)}</aside></section><section className="briefing-world-body"><div className="briefing-world-steps"><p>WHAT HAPPENS NEXT</p><article><span>01</span><h2>Tell us where to reach you.</h2><p>Name, work email, and company are enough. Add context only if it would make the conversation more useful.</p></article><article><span>02</span><h2>We prepare around your business.</h2><p>A senior team member reviews the request and brings the most relevant product, architecture, and evidence into the room.</p></article><article><span>03</span><h2>We work through it together.</h2><p>No generic product tour. The session stays focused on your workflow, constraints, and the clearest next decision.</p></article></div><div className="briefing-world-form"><div className="briefing-form-head"><span>BOOK THE BRIEFING</span><h2>Start with the basics.</h2><p>Comments are optional. We can explore the details together.</p></div>{status==="success"?<div className="briefing-form-result" role="status" aria-live="polite"><span>REQUEST RECEIVED</span><h3>We will review the request and reply shortly.</h3><p>Expect a focused response with the right people for the conversation.</p><button type="button" onClick={()=>setStatus("idle")}>Submit another request</button></div>:<form onSubmit={submitRequest}><input className="form-honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true"/><div className="field-row"><label>Name<input required name="name" autoComplete="name" maxLength={120}/></label><label>Work email<input required type="email" name="email" autoComplete="email" maxLength={160}/></label></div><label>Company<input required name="company" autoComplete="organization" maxLength={160}/></label><label>Anything we should know?<textarea name="comments" rows={4} maxLength={1200}/></label><button type="submit" disabled={status==="sending"}>{status==="sending"?"Sending request…":"Book the briefing ↗"}</button>{status==="error"&&<p className="form-error" role="alert">The secure submission service is not available right now. <a href={fallbackHref}>Send the prepared request by email</a>, or write to <a href="mailto:nishan@neurologicai.com">nishan@neurologicai.com</a>.</p>}<p>We use this information only to prepare and respond to your request. See our <Link href="/legal/privacy">privacy notice</Link>.</p></form>}</div></section></main><SiteFooter/></div>
}
