"use client";

import { NativeLink as Link } from "./native-link";
import { useEffect, useRef, useState } from "react";

export function Reveal({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  const ref = useRef<HTMLElement>(null);
  useEffect(() => { const el = ref.current; if (!el) return; const io = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { el.classList.add("is-visible"); io.disconnect(); } }, { threshold: .12 }); io.observe(el); return () => io.disconnect(); }, []);
  return <section ref={ref} className={`reveal ${className}`}>{children}</section>;
}

export function SiteHeader() {
  const [open, setOpen] = useState(false);
  const [openGroup, setOpenGroup] = useState<"platform"|"industries"|null>(null);
  const menuButtonRef=useRef<HTMLButtonElement>(null);
  const navRef=useRef<HTMLElement>(null);
  const closeMenu=()=>{setOpen(false);setOpenGroup(null)};
  useEffect(()=>{if(!open)return;const nav=navRef.current;const menuButton=menuButtonRef.current;const outside=[document.querySelector("main"),document.querySelector("footer")].filter(Boolean) as HTMLElement[];outside.forEach(el=>el.setAttribute("inert",""));const focusable=()=>[...(nav?.querySelectorAll<HTMLElement>('a[href],button:not([disabled])')||[])].filter(el=>el.offsetParent!==null);requestAnimationFrame(()=>focusable()[0]?.focus());const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape"){setOpen(false);setOpenGroup(null);return}if(e.key!=="Tab")return;const items=focusable();if(!items.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}};document.body.style.overflow="hidden";addEventListener("keydown",onKey);return()=>{document.body.style.overflow="";outside.forEach(el=>el.removeAttribute("inert"));removeEventListener("keydown",onKey);menuButton?.focus()}},[open]);
  return <header className="site-header">
    <Link href="#main" className="skip-link">Skip to content</Link>
    <div className="nav-wrap">
      <Link href="/" className="wordmark" aria-label="Corporate GPT home"><strong>CORPORATE GPT</strong><span><img src="/brand/neurologic-logogram-dark.png" alt="" width="150" height="134"/>BY NEUROLOGIC AI</span></Link>
      <button ref={menuButtonRef} className="menu-toggle" onClick={() => open?closeMenu():setOpen(true)} aria-expanded={open} aria-controls="primary-nav" aria-label={open?"Close menu":"Open menu"}><i/><i/></button>
      <nav ref={navRef} id="primary-nav" className={open ? "open" : ""} aria-label="Primary navigation" aria-modal={open||undefined} role={open?"dialog":undefined} onClick={e=>{if((e.target as HTMLElement).closest("a"))closeMenu()}}>
        <div className={`nav-group ${openGroup==="platform"?"expanded":""}`}>
          <button type="button" aria-expanded={openGroup==="platform"} aria-controls="platform-menu" onClick={()=>setOpenGroup(openGroup==="platform"?null:"platform")}>Platform <span aria-hidden="true">⌄</span></button>
          <div className="mega" id="platform-menu"><div><small>THE SYSTEM</small><Link href="/platform">Platform overview</Link><Link href="/deployment">Deployment & sovereignty</Link><Link href="/security">Security & compliance</Link></div><div><small>THE FIVE PILLARS</small><Link href="/platform/know">KNOW <em>01</em></Link><Link href="/platform/work">WORK <em>02</em></Link><Link href="/platform/learn" className="learn-link">LEARN <b>THE CORE</b></Link><Link href="/platform/build">BUILD <em>04</em></Link><Link href="/platform/trust">TRUST <em>05</em></Link></div></div>
        </div>
        <div className={`nav-group ${openGroup==="industries"?"expanded":""}`}>
          <button type="button" aria-expanded={openGroup==="industries"} aria-controls="industries-menu" onClick={()=>setOpenGroup(openGroup==="industries"?null:"industries")}>Industries <span aria-hidden="true">⌄</span></button>
          <div className="mega narrow" id="industries-menu"><div><small>INDUSTRY PACKS</small><Link href="/industries">All industries</Link><Link href="/industries/healthcare">Healthcare & med devices</Link><Link href="/industries/semiconductor">Semiconductor</Link><Link href="/industries/government">Government & public sector</Link><Link href="/industries/manufacturing">Manufacturing & industrial</Link><Link href="/industries/retail">Retail & hospitality</Link></div></div>
        </div>
        <Link href="/proof">Proof</Link><Link href="/pricing">Commercial model</Link><Link href="/partners">Partners</Link><Link href="/company">Company</Link><Link href="/briefing" className="nav-cta">Request a briefing</Link>
      </nav>
    </div>
  </header>;
}

export function SiteFooter() { return <footer className="site-footer"><div className="container"><div className="footer-head"><div><Link href="/" className="footer-mark">CORPORATE GPT</Link><p>Sovereign enterprise search, governed work, and agents inside the agreed boundary.</p></div><a className="neurologic-lockup" href="https://www.neurologicai.com" target="_blank" rel="noreferrer"><img src="/brand/neurologic-logo-white.png" alt="Neurologic AI" width="698" height="134" loading="lazy" decoding="async"/><span>THE APPLIED AI LAB · UNITED STATES · DUBAI · INDIA ↗</span></a></div><div className="footer-grid"><nav aria-label="Platform links"><small>PLATFORM</small><Link href="/platform">Overview</Link><Link href="/platform/know">KNOW</Link><Link href="/platform/work">WORK</Link><Link href="/platform/learn">LEARN — the core</Link><Link href="/platform/build">BUILD</Link><Link href="/platform/trust">TRUST</Link></nav><nav aria-label="Explore links"><small>EXPLORE</small><Link href="/deployment">Deployment</Link><Link href="/security">Security</Link><Link href="/industries">Industries</Link><Link href="/proof">Proof</Link><Link href="/pricing">Commercial model</Link></nav><nav aria-label="Company links"><small>COMPANY</small><Link href="/company">About & team</Link><Link href="/partners">Partners</Link><Link href="/resources">Resources</Link><a href="mailto:careers@neurologicai.com">Careers</a></nav><nav aria-label="Legal and trust links"><small>LEGAL & TRUST</small><Link href="/legal/privacy">Privacy</Link><Link href="/legal/terms">Terms</Link><Link href="/legal/subprocessors">Subprocessors</Link><span className="trust-badge">CUSTOMER-HOSTED OPTIONS</span><span className="trust-badge">DOCUMENTED DATA PATHS</span><span className="trust-badge">SECURITY PACK ON REQUEST</span></nav></div><div className="footer-bottom"><span>© 2026 Neurologic AI</span><span>Customer claims are labeled by deployment status.</span><span>No advertising pixels.</span></div></div></footer> }

export function CurveModule() { return <div className="curve-module" role="img" aria-label="Proof-of-learning curve rises from a 72 percent baseline to 86 percent after two adapter refreshes"><div className="curve-head"><span>PROOF-OF-LEARNING</span><span>YOUR EVAL SET · Q1—Q4</span></div><svg viewBox="0 0 620 400" aria-hidden="true"><g className="grid-lines"><path d="M60 40V340H580"/><path d="M60 280H580M60 220H580M60 160H580M60 100H580"/></g><path className="curve-area" d="M60 300 C135 294 155 267 220 260 S320 209 375 194 S470 115 580 80 L580 340 L60 340Z"/><path className="curve-line" d="M60 300 C135 294 155 267 220 260 S320 209 375 194 S470 115 580 80"/><g className="dots"><circle cx="60" cy="300" r="5"/><circle cx="220" cy="260" r="5"/><circle cx="375" cy="194" r="5"/><circle cx="580" cy="80" r="6"/></g><g className="curve-labels"><text x="60" y="370">Q1 BASELINE</text><text x="205" y="245">ADAPTER REFRESH</text><text x="355" y="178">+8%</text><text x="500" y="62">+14% ON YOUR TASKS</text></g></svg><div className="curve-foot"><span>MODEL 2.4 · DEPLOYED</span><strong>86.2% <em>↑14.1%</em></strong></div></div> }

export function LoopDiagram() { const steps = ["USE", "CAPTURE", "CURATE", "TRAIN", "EVALUATE", "DEPLOY"]; return <div className="loop-diagram" role="img" aria-label="Closed learning loop: use, capture, curate, train, evaluate, deploy"><div className="loop-frame-label">YOUR PERIMETER</div><div className="loop-center"><b>Closed</b><span>learning loop</span></div>{steps.map((step, i) => <div key={step} className={`loop-step step-${i}`}><span>{String(i+1).padStart(2,"0")}</span>{step}</div>)}</div> }

export function Ladder() { const items = [["01","General chat","Fluent, but knows nothing about your enterprise"],["02","Enterprise search","Finds documents, takes no action"],["03","Document intelligence","Reads deeply, learns nothing organizationally"],["04","Adaptive Enterprise Intelligence","Connects, acts, remembers, and learns your company"]]; return <div className="ladder container">{items.map(([n,title,body],i) => <div key={n} className={i===3?"active":""} style={{"--step": i} as React.CSSProperties}><span>{n}</span><h3>{title}</h3><p>{body}</p>{i===3&&<em>THE CATEGORY WE BUILT</em>}</div>)}</div> }
