"use client";

import { useEffect } from "react";
import { NativeLink as Link } from "./native-link";
import type { PageContent } from "../content";
import { SiteFooter, SiteHeader } from "./site";

type RouteFact = { value: string; label: string };
type Journey = { title: string; body: string; tag: string };

const routeFacts: Record<string, RouteFact[]> = {
  platform: [{value:"05",label:"integrated pillars"},{value:"01",label:"governance plane"},{value:"00",label:"required data egress"}],
  "platform/know": [{value:"50+",label:"connector patterns"},{value:"2×",label:"validation stages"},{value:"100%",label:"claims cited or refused"}],
  "platform/work": [{value:"02",label:"modes: quick + deep"},{value:"HITL",label:"approval where required"},{value:"1",label:"persistent work surface"}],
  "platform/learn": [{value:"05",label:"learning depths"},{value:"0",label:"external training path"},{value:"Q/Q",label:"proof-of-learning review"}],
  "platform/build": [{value:"04",label:"enterprise SDKs"},{value:"1",label:"private marketplace"},{value:"RBAC",label:"least-privilege scopes"}],
  "platform/trust": [{value:"04",label:"control gates"},{value:"CMK",label:"customer-managed keys"},{value:"SIEM",label:"audit export"}],
  deployment: [{value:"03",label:"deployment blueprints"},{value:"12",label:"reference weeks to scale"},{value:"YOU",label:"own infrastructure + weights"}],
  security: [{value:"0",label:"required data egress"},{value:"CMK",label:"encryption ownership"},{value:"4×",label:"control planes"}],
  pricing: [{value:"FLAT",label:"enterprise licensing"},{value:"90D",label:"structured pilot"},{value:"0",label:"per-seat penalties"}],
  partners: [{value:"AWS",label:"Activate program"},{value:"NVIDIA",label:"Connect program"},{value:"03",label:"partner motions"}],
  resources: [{value:"03",label:"research tracks"},{value:"01",label:"working-day bootcamp"},{value:"NO",label:"content-farm filler"}],
  proof: [{value:"03",label:"named customer stories"},{value:"03",label:"experience deployments"},{value:"04",label:"evidence statuses"}],
  company: [{value:"300–400%",label:"company-reported YoY growth"},{value:"03",label:"operating regions"},{value:"02",label:"US patents"}],
  industries: [{value:"05",label:"industry operating models"},{value:"03",label:"named proof anchors"},{value:"01",label:"sovereign platform"}],
  "industries/healthcare": [{value:"5,000",label:"on-prem users"},{value:"4–5×",label:"reported review acceleration"},{value:"HITL",label:"human review retained"}],
  "industries/semiconductor": [{value:"POC",label:"paid engagement status"},{value:"0",label:"IP leaves boundary"},{value:"4",label:"agent-loop stages"}],
  "industries/government": [{value:"LIVE",label:"public deployment"},{value:"24/7",label:"official-source guidance"},{value:"UAE",label:"in-region story"}],
  "industries/manufacturing": [{value:"OT/IT",label:"boundary-aware design"},{value:"04",label:"plant workflows"},{value:"PLAYBOOK",label:"solution status"}],
  "industries/retail": [{value:"03",label:"field experiences"},{value:"VOICE",label:"drive-through agent"},{value:"TH",label:"mall + duty-free"}],
};

const productImages: Record<string,string> = {
  "platform/know":"/product/enterprise-search.png",
  "platform/work":"/product/ai-workspace.png",
  "platform/build":"/product/agent-builder.png",
};

const journeys: Record<string, Journey[]> = {
  "platform/know":[
    {tag:"01 · QUESTION",title:"Ask in the language of work.",body:"A natural-language question becomes a multi-source investigation, not a keyword search."},
    {tag:"02 · DISCOVER",title:"Find evidence across systems.",body:"Permission-aware retrieval assembles tickets, documents, conversations, meetings, and live databases."},
    {tag:"03 · VALIDATE",title:"Inspect the evidence first.",body:"The source set is visible before generation. Remove weak evidence or switch to verbatim mode."},
    {tag:"04 · ANSWER",title:"Cite it—or refuse it.",body:"Every material claim points back to a passage. Unsupported conclusions stop visibly."},
  ],
  "platform/work":[
    {tag:"01 · BRIEF",title:"Start with an outcome.",body:"Give the coworker a deliverable, files, constraints, collaborators, and the definition of done."},
    {tag:"02 · PLAN",title:"A transparent work plan.",body:"The system decomposes the engagement and shows which tools, data, and specialist agents it will use."},
    {tag:"03 · EXECUTE",title:"Work happens in the workspace.",body:"Analysis, writing, code, spreadsheets, and presentations remain attached to one persistent engagement."},
    {tag:"04 · APPROVE",title:"People stay in the consequential loop.",body:"Policy-shaped gates pause execution for human review before a sensitive action or publication."},
    {tag:"05 · DELIVER",title:"A finished artifact, not a chat log.",body:"The output is delivered in the format the business needs, with its evidence and audit trail attached."},
  ],
  "platform/learn":[
    {tag:"01 · SIGNAL",title:"Useful work produces signals.",body:"Corrections, accepted outputs, expert edits, and task results become candidate learning evidence."},
    {tag:"02 · CURATE",title:"Permission and provenance first.",body:"Only approved material enters a versioned training set linked to owners, sources, and retention policy."},
    {tag:"03 · ADAPT",title:"Train inside the perimeter.",body:"A customer-specific adapter learns vocabulary, judgment, systems, domain, and craft on customer GPUs."},
    {tag:"04 · EVALUATE",title:"Regression gates decide.",body:"Candidate and baseline are compared on a gold set. Nothing that regresses is promoted."},
    {tag:"05 · DEPLOY",title:"Ship, observe, roll back.",body:"Signed versions canary, hot-swap, and remain reversible. The quarter closes with a proof readout."},
  ],
  "platform/build":[
    {tag:"01 · DEFINE",title:"Start with a capability manifest.",body:"Purpose, tools, inputs, outputs, owner, and least-privilege scopes are explicit before assembly."},
    {tag:"02 · COMPOSE",title:"Build the workflow visually.",body:"Connect triggers, systems, specialist agents, memory, and deterministic business logic."},
    {tag:"03 · TEST",title:"Golden cases before users.",body:"Run scenario tests, adversarial cases, permission checks, and cost thresholds against a candidate version."},
    {tag:"04 · GOVERN",title:"Approval is part of the design.",body:"Security and business owners sign the exact version and scopes that may enter production."},
    {tag:"05 · PUBLISH",title:"One capability. Enterprise-wide reuse.",body:"Release to the private marketplace with status, lineage, ratings, rollback, and an accountable owner."},
  ],
  "platform/trust":[
    {tag:"GATE 01 · ACCESS",title:"Can this person see it?",body:"Identity, directory groups, document permissions, and customer-managed keys resolve before retrieval."},
    {tag:"GATE 02 · GUARDRAILS",title:"May the model process it?",body:"Policy, PII handling, prompt and output scanning, and action scopes shape the permitted path."},
    {tag:"GATE 03 · AUDIT",title:"Can the decision be reconstructed?",body:"Question, evidence, model, output, tool calls, approvals, cost, and outcome become one attributable event."},
    {tag:"GATE 04 · LEARNING",title:"May the system learn it?",body:"Training permission is distinct from viewing permission. Provenance follows every adapter candidate."},
  ],
};

const groupLinks: Record<string,{label:string;href:string}[]> = {
  platform:[{label:"Overview",href:"/platform"},{label:"Know",href:"/platform/know"},{label:"Work",href:"/platform/work"},{label:"Learn",href:"/platform/learn"},{label:"Build",href:"/platform/build"},{label:"Trust",href:"/platform/trust"}],
  industries:[{label:"Overview",href:"/industries"},{label:"Healthcare",href:"/industries/healthcare"},{label:"Semiconductor",href:"/industries/semiconductor"},{label:"Government",href:"/industries/government"},{label:"Manufacturing",href:"/industries/manufacturing"},{label:"Retail",href:"/industries/retail"}],
  company:[{label:"Proof",href:"/proof"},{label:"Company",href:"/company"},{label:"Partners",href:"/partners"},{label:"Resources",href:"/resources"}],
  trust:[{label:"Deployment",href:"/deployment"},{label:"Security",href:"/security"},{label:"Pricing",href:"/pricing"}],
};

function WorldMotion(){useEffect(()=>{const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const reveal=[...document.querySelectorAll<HTMLElement>("[data-world-reveal]")];const io=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){(entry.target as HTMLElement).classList.add("is-visible");io.unobserve(entry.target)}}),{threshold:.1,rootMargin:"0px 0px -8%"});reveal.forEach(el=>io.observe(el));const films=[...document.querySelectorAll<HTMLElement>("[data-world-film]")];let frame=0,queued=false;const update=()=>{queued=false;films.forEach(el=>{const rect=el.getBoundingClientRect();const span=Math.max(1,rect.height-innerHeight);const progress=Math.max(0,Math.min(1,-rect.top/span));const count=Number(el.dataset.beats||5);const beat=Math.min(count-1,Math.floor(progress*count));el.style.setProperty("--world-p",String(reduced?1:progress));el.dataset.beat=String(reduced?count-1:beat)})};const request=()=>{if(!queued){queued=true;frame=requestAnimationFrame(update)}};addEventListener("scroll",request,{passive:true});addEventListener("resize",request,{passive:true});request();return()=>{cancelAnimationFrame(frame);removeEventListener("scroll",request);removeEventListener("resize",request);io.disconnect()}},[]);return null}

function routeGroup(id:string){if(id==="platform"||id.startsWith("platform/"))return "platform";if(id==="industries"||id.startsWith("industries/"))return "industries";if(["proof","company","partners","resources"].includes(id))return "company";return "trust"}

function SectionNav({id}:{id:string}){const links=groupLinks[routeGroup(id)]||[];return <nav className="world-subnav" aria-label="Section navigation"><span>{routeGroup(id).toUpperCase()}</span><div>{links.map(link=><Link className={link.href===`/${id}`?"active":""} href={link.href} key={link.href}>{link.label}</Link>)}</div></nav>}

function ClientLogo({name,src}:{name:string;src?:string}){return <div className="client-logo">{src?<img src={src} alt={`${name} logo`}/>:<strong>{name}</strong>}</div>}

function HeroObject({id}:{id:string}){
  if(productImages[id])return <div className="world-product-object"><span>LIVE PRODUCT SURFACE</span><img src={productImages[id]} alt="Corporate GPT product interface"/><i>PERMISSIONED · AUDITED · CUSTOMER-HOSTED</i></div>;
  if(id==="proof")return <div className="world-logo-object"><ClientLogo name="Micron" src="/clients/micron.png"/><ClientLogo name="Globus Medical" src="/clients/globus-medical.png"/><ClientLogo name="Dubai CommerCity" src="/clients/dubai-commercity.svg"/><ClientLogo name="Skan AI" src="/clients/skan-ai.svg"/></div>;
  if(id==="company")return <div className="world-map-object"><span className="map-line"/><b className="pin us">US <small>COMPANY</small></b><b className="pin uae">UAE <small>DIFC AI CAMPUS</small></b><b className="pin india">INDIA <small>ENGINEERING</small></b><strong>NEUROLOGIC AI</strong></div>;
  if(id==="partners")return <div className="world-partner-object"><div><strong>AWS</strong><span>ACTIVATE PROGRAM</span><i>ACCEPTED</i></div><div><strong>NVIDIA</strong><span>CONNECT PROGRAM</span><i>PROGRAM STATUS</i></div><small>STATUS AS PROVIDED BY NEUROLOGIC AI</small></div>;
  if(id==="pricing")return <div className="world-tco-object"><span>MODELED COST / USER</span><div className="tco-chart"><i className="rent"/><i className="own"/><b className="rent-label">RENTED · PER SEAT</b><b className="own-label">OWNED · FLAT</b></div><small>ASSUMPTIONS SHARED IN THE FIRST BRIEFING</small></div>;
  if(id==="resources")return <div className="world-cover-object"><article><span>01</span><b>THE GAUNTLET REPORT</b><small>RESEARCH · IN PREPARATION</small></article><article><span>02</span><b>OWNED VS. RENTED</b><small>FIELD MODEL · BRIEFING EDITION</small></article><article><span>03</span><b>LEARNING LAYER</b><small>SECURITY NOTE · IN PREPARATION</small></article></div>;
  if(id==="deployment")return <div className="world-topology-object"><span>YOUR CONTROL PLANE</span><div><b>CLOUD TENANT</b><b>PRIVATE CLOUD</b><b>AIR-GAPPED</b></div><strong>ONE PLATFORM · THREE VALIDATED SHAPES</strong></div>;
  if(id==="security"||id==="platform/trust")return <div className="world-control-object"><span>TRUST CONTROL PLANE</span>{["IDENTITY","POLICY","AUDIT","LEARNING"].map((x,i)=><i key={x} style={{"--c":i} as React.CSSProperties}>{x}</i>)}<b>REQUEST<br/>ALLOWED</b><small>EVERY DECISION RECONSTRUCTABLE</small></div>;
  if(id==="platform/learn")return <div className="world-eval-object"><span>PROOF OF LEARNING · ILLUSTRATIVE</span><div className="eval-chart"><i/><i/><i/><i/></div><strong>CANDIDATE <em>PASS</em></strong><small>BASELINE · CANDIDATE · DEPLOYED · ROLLBACK READY</small></div>;
  if(id.startsWith("industries/"))return <IndustryHeroObject id={id}/>;
  return <div className="world-system-object"><span>CUSTOMER SECURITY BOUNDARY</span><div className="system-orbit">{["KNOW","WORK","LEARN","BUILD"].map((x,i)=><i key={x} style={{"--o":i} as React.CSSProperties}>{x}</i>)}<b>AEI<small>ADAPTIVE<br/>ENTERPRISE<br/>INTELLIGENCE</small></b></div><strong>TRUST · CONTROL PLANE</strong></div>;
}

function IndustryHeroObject({id}:{id:string}){const data:Record<string,{client:string;src?:string;status:string;steps:string[]}>= {
  "industries/healthcare":{client:"Globus Medical",src:"/clients/globus-medical.png",status:"PRODUCTION · ON-PREM",steps:["CONTROLLED DOCS","CITED REVIEW","HUMAN SIGN-OFF"]},
  "industries/semiconductor":{client:"Micron",src:"/clients/micron.png",status:"PAID POC",steps:["SIMULATE","REVIEW","REVISE","RE-RUN"]},
  "industries/government":{client:"Dubai CommerCity",src:"/clients/dubai-commercity.svg",status:"PUBLIC-LIVE",steps:["PUBLIC QUESTION","OFFICIAL SOURCE","CITED ANSWER"]},
  "industries/manufacturing":{client:"Industrial knowledge playbook",status:"SOLUTION PLAYBOOK",steps:["MACHINE + SOP","EXPERT SIGNAL","SHIFT ANSWER"]},
  "industries/retail":{client:"Three field experiences",status:"BUILT FOR OPERATIONS",steps:["VOICE AGENT","MALL ASSISTANT","DUTY-FREE"]},
};const item=data[id];return <div className="industry-hero-object"><div><ClientLogo name={item.client} src={item.src}/><span>{item.status}</span></div><div className="industry-flow">{item.steps.map((step,i)=><span key={step}><i>0{i+1}</i>{step}</span>)}</div><small>WORKFLOW · BOUNDARY · EVIDENCE</small></div>}

function WorldHero({id,page,compact=false}:{id:string;page:PageContent;compact?:boolean}){const facts=routeFacts[id]||page.stats||[];return <section className={`world-hero ${compact?"compact":""}`}><div className="world-hero-grid"><div className="world-hero-copy" data-world-reveal><div className="world-breadcrumb"><span>{page.label}</span><i>{id.replaceAll("/"," / ")}</i></div><h1>{page.hero}</h1><p>{page.intro}</p><div className="world-hero-actions"><Link href="/briefing">Scope your deployment <span>↗</span></Link>{!compact&&<a href="#experience">Enter the system <span>↓</span></a>}</div></div><HeroObject id={id}/></div>{facts.length>0&&<div className="world-fact-rail">{facts.slice(0,3).map(f=><div key={f.value+f.label}><strong>{f.value}</strong><span>{f.label}</span></div>)}</div>}</section>}

const aeiBeats=[
  {tag:"01 · KNOW",title:"Evidence enters with its permissions intact.",body:"Documents, databases, meetings, people, and systems resolve into cited context. Every source retains ownership, freshness, and access policy."},
  {tag:"02 · WORK",title:"Context becomes governed action.",body:"The workspace plans, uses tools, coordinates specialist agents, and pauses for a person wherever the business requires approval."},
  {tag:"03 · LEARN",title:"Accepted work becomes a compounding asset.",body:"Corrections and outcomes create permissioned training candidates. Adapters are evaluated on your gold set before promotion."},
  {tag:"04 · BUILD",title:"Repeated work becomes reusable capability.",body:"Approved patterns become skills, agents, connectors, and widgets in a private enterprise marketplace."},
  {tag:"05 · TRUST",title:"Governance is the perimeter—not a plugin.",body:"Identity, policy, provenance, audit, model control, evaluation, and unlearning surround every earlier step."},
];

function AeiSystemFilm(){return <section className="aei-film" data-world-film data-beats="5" data-beat="0" id="experience"><div className="aei-stage"><div className="aei-copy"><p>ADAPTIVE ENTERPRISE INTELLIGENCE</p>{aeiBeats.map((beat,i)=><article key={beat.tag} data-scene={i}><span>{beat.tag}</span><h2>{beat.title}</h2><p>{beat.body}</p></article>)}<div className="aei-progress"><i/></div></div><figure className="aei-map"><div className="aei-boundary"><span>TRUST · CUSTOMER CONTROL PLANE</span></div><div className="aei-data-sources"><b>ERP</b><b>DOCS</b><b>DB</b><b>PEOPLE</b></div><div className="aei-node know"><span>01</span><b>KNOW</b><small>Citations<br/>Sources<br/>Refusals</small></div><div className="aei-node work"><span>02</span><b>WORK</b><small>Plans<br/>Tools<br/>Approvals</small></div><div className="aei-node learn"><span>03</span><b>LEARN</b><small>Curate → Adapt<br/>Evaluate → Ship</small></div><div className="aei-node build"><span>04</span><b>BUILD</b><small>Skills<br/>Agents<br/>Marketplace</small></div><div className="aei-edge edge-a"><i/></div><div className="aei-edge edge-b"><i/></div><div className="aei-edge edge-c"><i/></div><div className="aei-proof-dock"><span>ACTIVE EVIDENCE</span><div className="dock-scenes"><div>CITATION PACKET <b>12 SOURCES</b></div><div>APPROVAL GATE <b>HUMAN REVIEW</b></div><div>EVAL CANDIDATE <b>PASS</b></div><div>CAPABILITY <b>PUBLISHED</b></div><div>AUDIT EVENT <b>SEALED</b></div></div></div><figcaption>Enterprise evidence flows through KNOW, WORK, LEARN, and BUILD while TRUST encloses the entire system.</figcaption></figure><div className="aei-chapters">{aeiBeats.map((x,i)=><span key={x.tag}>{String(i+1).padStart(2,"0")}</span>)}</div></div></section>}

function JourneyFilm({id}:{id:string}){const beats=journeys[id];if(!beats)return null;const image=productImages[id];return <section className={`journey-film journey-${id.split("/").pop()}`} data-world-film data-beats={beats.length} data-beat="0" id="experience"><div className="journey-stage"><div className="journey-copy"><p>THE OPERATING SEQUENCE</p>{beats.map((beat,i)=><article key={beat.tag} data-scene={i}><span>{beat.tag}</span><h2>{beat.title}</h2><p>{beat.body}</p></article>)}<div className="journey-progress"><i/></div></div><figure className="journey-canvas">{image&&<img src={image} alt="Corporate GPT product interface"/>}<div className="journey-grid"/><div className="journey-events">{beats.map((beat,i)=><div key={beat.tag} data-scene={i}><span>{beat.tag}</span><b>{beat.title}</b><small>{id.includes("learn")?i===3?"EVALUATION PASSED":"PROVENANCE ATTACHED":id.includes("trust")?i===0?"IDENTITY RESOLVED":"POLICY EVENT LOGGED":i===beats.length-1?"READY FOR RELEASE":"SYSTEM ACTIVE"}</small></div>)}</div><div className="journey-status"><i/><span>INSIDE CUSTOMER PERIMETER</span><b>{id.split("/").pop()?.toUpperCase()}</b></div><figcaption>{beats.map(x=>x.title).join(" ")}</figcaption></figure></div></section>}

function ContentAtlas({page}:{page:PageContent}){return <section className="content-atlas"><div className="atlas-intro" data-world-reveal><p>CAPABILITY ATLAS</p><h2>The detail beneath<br/><em>the experience.</em></h2><span>Product, operating model, controls, and ownership—made concrete enough for a technical review.</span></div>{page.blocks.map((block,index)=><article className={`atlas-row items-${block.items?.length||0}`} key={block.title} data-world-reveal><div className="atlas-index"><span>{String(index+1).padStart(2,"0")}</span><i>{block.label}</i></div><div className="atlas-main"><h3>{block.title}</h3>{block.body&&<p>{block.body}</p>}{block.note&&<small>{block.note}</small>}</div>{block.items&&<div className="atlas-items">{block.items.map((item,i)=><div key={item.title}><span>{String(i+1).padStart(2,"0")}</span><h4>{item.title}</h4><p>{item.body}</p>{item.metric&&<em>{item.metric}<small> · VERIFY IN BRIEFING</small></em>}</div>)}</div>}</article>)}</section>}

const proofCases=[
  {name:"Micron",logo:"/clients/micron.png",status:"PAID PROOF OF CONCEPT",sector:"SEMICONDUCTOR",headline:"An engineering loop that can simulate, review, revise, and re-run.",constraint:"Sensitive engineering context remains inside the approved environment.",workflow:["Simulate","Review","Revise","Re-run"],outcome:"Autonomous orchestration demonstrated inside the agreed POC scope. Production status is not implied."},
  {name:"Globus Medical",logo:"/clients/globus-medical.png",status:"PRODUCTION · ON-PREMISES",sector:"MEDICAL DEVICES",headline:"Enterprise AI under healthcare-grade review—at 5,000-user scale.",constraint:"Controlled documents, permissions, human review, and customer-owned infrastructure.",workflow:["Retrieve","Cite","Review","Decide"],outcome:"4–5× faster research review is a Neurologic AI–reported customer outcome; measurement detail is shared in briefing."},
  {name:"Dubai CommerCity",logo:"/clients/dubai-commercity.svg",status:"PUBLIC-LIVE",sector:"UAE GOVERNMENT FREE ZONE",headline:"Founder guidance grounded in official regulations, around the clock.",constraint:"Public answers must stay inside official sources and remain defensible line by line.",workflow:["Question","Official source","Cited answer","Escalate"],outcome:"24/7 availability describes service coverage, not an adoption or productivity metric."},
  {name:"Skan AI",logo:"/clients/skan-ai.svg",status:"CLIENT COLLABORATION",sector:"ENTERPRISE PROCESS INTELLIGENCE",headline:"Enterprise AI built around the real shape of work.",constraint:"Customer-approved public detail is intentionally limited.",workflow:["Observe","Contextualize","Govern","Act"],outcome:"Case detail and customer voice remain subject to publication approval."},
];
const fieldCases=[
  {name:"Burger-chain drive-through",status:"VOICE AGENT · CUSTOMER NAME WITHHELD",body:"Noise-aware speech → menu grounding → order confirmation → POS handoff → human escalation."},
  {name:"Thailand mall assistant",status:"MULTILINGUAL ASSISTANT · CUSTOMER NAME WITHHELD",body:"Wayfinding, tenant discovery, events, services, and escalation across a physical destination."},
  {name:"Thailand duty-free",status:"RETAIL CONCIERGE · CUSTOMER NAME WITHHELD",body:"Product discovery, availability, brand knowledge, language support, and staff handoff."},
];

function ProofLibrary(){return <><section className="proof-library" id="experience"><div className="proof-library-head"><p>CUSTOMER EVIDENCE</p><h2>Every case carries<br/><em>its status.</em></h2><span>Production is not a POC. Availability is not ROI. Modeled is not measured. We label the difference.</span></div>{proofCases.map((c,i)=><article key={c.name} data-world-reveal><div className="proof-case-brand"><span>0{i+1} · {c.sector}</span><ClientLogo name={c.name} src={c.logo}/><i>{c.status}</i></div><div className="proof-case-story"><h3>{c.headline}</h3><p>{c.constraint}</p><div>{c.workflow.map((x,j)=><span key={x}><i>0{j+1}</i>{x}</span>)}</div><small>EVIDENCE NOTE</small><p>{c.outcome}</p></div></article>)}</section><section className="field-proof"><div><p>FIELD EXPERIENCES</p><h2>Three operational agents.<br/><em>Three different realities.</em></h2></div><div>{fieldCases.map((x,i)=><article key={x.name} data-world-reveal><span>0{i+1}</span><small>{x.status}</small><h3>{x.name}</h3><p>{x.body}</p></article>)}</div></section></>}

const industryData:Record<string,{client?:string;logo?:string;status:string;headline:string;systems:string[];steps:{title:string;body:string}[];evidence:string}>= {
  "industries/healthcare":{client:"Globus Medical",logo:"/clients/globus-medical.png",status:"PRODUCTION · 5,000 USERS · ON-PREM",headline:"Controlled knowledge moves from source to decision without losing permission, citation, or human review.",systems:["Controlled documents","Quality systems","SOPs + CAPA","Clinical enablement"],steps:[{title:"Assemble",body:"Retrieve technique guides, device documentation, cases, and approved internal references."},{title:"Validate",body:"Expose the exact evidence set and reject stale, out-of-scope, or inaccessible material."},{title:"Draft",body:"Generate cited research and preparation outputs inside a governed workspace."},{title:"Approve",body:"Retain expert sign-off and a reconstructable record of the evidence used."}],evidence:"Reported scale and acceleration are company-supplied customer outcomes. Control applicability depends on the deployed workflow and customer environment."},
  "industries/semiconductor":{client:"Micron",logo:"/clients/micron.png",status:"PAID POC · CONTROLLED SCOPE",headline:"The agent loop runs where engineering IP is allowed to exist—and nowhere else.",systems:["Simulation tools","Design artifacts","Engineering rules","Review feedback"],steps:[{title:"Simulate",body:"An orchestrator invokes the approved engineering workflow and records the candidate output."},{title:"Review",body:"Specialist agents and deterministic checks compare the result against the agreed criteria."},{title:"Revise",body:"The workflow identifies a permitted change, attaches reasoning, and preserves the prior state."},{title:"Re-run",body:"A new result is produced, compared, and escalated when confidence or policy requires an engineer."}],evidence:"Paid proof-of-concept, not presented as a production rollout. Public detail is deliberately limited to the approved workflow shape."},
  "industries/government":{client:"Dubai CommerCity",logo:"/clients/dubai-commercity.svg",status:"PUBLIC-LIVE · UAE",headline:"A public question becomes an official-source answer with its evidence visible.",systems:["Official regulations","Program pages","Founder guidance","Public web"],steps:[{title:"Ask",body:"A founder or citizen asks in natural language, without learning an institutional taxonomy."},{title:"Constrain",body:"Retrieval is limited to the approved official corpus and current publication set."},{title:"Cite",body:"The answer points back to the source passage and refuses unsupported policy interpretation."},{title:"Escalate",body:"Unresolved or sensitive questions route to the appropriate human channel."}],evidence:"24/7 refers to service availability. Arabic and additional service metrics should be presented only when verified as live."},
  "industries/manufacturing":{status:"SOLUTION PLAYBOOK · NO NAMED PROOF SHOWN",headline:"Machine history, engineering change, and human know-how become one permissioned operating memory.",systems:["MES + ERP","PLM + BOM","Maintenance logs","Shift knowledge"],steps:[{title:"Capture",body:"Connect approved plant and enterprise sources without forcing operational data into a public service."},{title:"Reconcile",body:"Resolve conflicting revisions, equipment identities, suppliers, and known exceptions."},{title:"Assist",body:"Deliver cited troubleshooting, BOM, maintenance, and supplier-quality context by role."},{title:"Learn",body:"Promote repeated expert corrections into governed knowledge and skill candidates."}],evidence:"This page is a solution playbook. Outcome ranges must be modeled with the customer before publication."},
  "industries/retail":{status:"THREE BUILT EXPERIENCES · CUSTOMER NAMES WITHHELD",headline:"Voice, destination, and product intelligence designed around the moment the customer needs help.",systems:["Voice + menu","Wayfinding + events","Catalog + inventory","POS + human handoff"],steps:[{title:"Drive-through voice",body:"Handle noise, accents, menu rules, order confirmation, POS handoff, and a fast human fallback."},{title:"Mall assistant",body:"Guide visitors across stores, events, services, and wayfinding in the language they choose."},{title:"Duty-free concierge",body:"Ground product discovery in availability, brand knowledge, traveller context, and staff escalation."},{title:"Operations layer",body:"Give staff a governed source for policy, procedures, service standards, and live exceptions."}],evidence:"Client identities and measured service outcomes are withheld until publication approval. The workflow detail reflects delivered solution patterns."},
};

function IndustryStory({id}:{id:string}){const data=industryData[id];return <><section className="industry-case" id="experience"><div className="industry-case-brand" data-world-reveal>{data.client&&<ClientLogo name={data.client} src={data.logo}/>}<span>{data.status}</span><h2>{data.headline}</h2><div>{data.systems.map(x=><i key={x}>{x}</i>)}</div></div><div className="industry-workflow">{data.steps.map((step,i)=><article key={step.title} data-world-reveal><span>0{i+1}</span><h3>{step.title}</h3><p>{step.body}</p><i/></article>)}</div><p className="industry-evidence"><span>EVIDENCE & SCOPE</span>{data.evidence}</p></section></>}

const industryIndex=[
  {n:"01",name:"Healthcare & medical devices",status:"NAMED PRODUCTION PROOF",href:"/industries/healthcare",body:"Controlled-document intelligence, regulatory research, quality workflows, and clinical enablement under human review."},
  {n:"02",name:"Semiconductor",status:"NAMED PAID POC",href:"/industries/semiconductor",body:"Autonomous engineering orchestration inside the boundary where process and design IP is allowed to exist."},
  {n:"03",name:"Government & public sector",status:"NAMED PUBLIC-LIVE",href:"/industries/government",body:"Official-source guidance for founders and citizens, deployed in-region and defensible line by line."},
  {n:"04",name:"Manufacturing & industrial",status:"SOLUTION PLAYBOOK",href:"/industries/manufacturing",body:"Plant, product, supplier, maintenance, and expert knowledge joined into one governed operating memory."},
  {n:"05",name:"Retail & hospitality",status:"THREE BUILT EXPERIENCES",href:"/industries/retail",body:"Drive-through voice, destination assistance, duty-free concierge, and frontline operations intelligence."},
];
function IndustriesIndex(){return <section className="industries-index" id="experience"><div><p>FIVE OPERATING MODELS</p><h2>Same platform.<br/><em>Different consequences.</em></h2><span>Every vertical starts from its data boundary, workflow, approval chain, and evidence standard—not a stock photograph.</span></div>{industryIndex.map(x=><Link href={x.href} key={x.name} data-world-reveal><span>{x.n}</span><small>{x.status}</small><h3>{x.name}</h3><p>{x.body}</p><b>Explore operating model ↗</b></Link>)}</section>}

const leaders=[
  {initials:"SD",name:"Dr. Santanu Das",role:"Chairman of the Board",bio:"PhD in Electrical Engineering, Washington University."},
  {initials:"JG",name:"John Gillotte",role:"Co-Founder & CTO",bio:"BS in Computer Science, University of Michigan."},
  {initials:"NA",name:"Nishan Ali",role:"Founder & CEO",bio:"M.Tech in Artificial Intelligence, IIT Jodhpur."},
  {initials:"PD",name:"Pranta Das",role:"Lead Data Scientist",bio:"Leads data-science delivery across model development, evaluation, and customer-specific solution design."},
  {initials:"SM",name:"Soulina Mondal",role:"Associate ML Engineer",bio:"Builds and operationalizes machine-learning systems across the applied AI portfolio."},
  {initials:"SS",name:"Suchi Sharma",role:"Robotics Simulation Engineer",bio:"Works across intelligent robotics, digital twins, synthetic data, and simulation-led deployment."},
];

function CompanyStory(){const history=[{year:"2017–23",title:"The production foundation",body:"Nine years of applied data-science work across healthcare, enterprise systems, computer vision, NLP, and MLOps."},{year:"2024",title:"Neurologic AI scales",body:"The company expands its applied AI team and receives the Times Business Award."},{year:"2025",title:"Healthcare recognition",body:"Times Health Award for generative AI in health, alongside continued customer and product growth."},{year:"2026",title:"Global operating shape",body:"Back-to-back health recognition, Dubai registration under an AI license at DIFC AI Campus, and a US–UAE–India operating footprint."}];return <><section className="company-purpose" id="experience"><div data-world-reveal><span>MISSION</span><h2>Democratize production-grade AI.</h2><p>Make advanced, governed intelligence accessible to enterprises of every size—without asking them to surrender their data, control, or institutional knowledge.</p></div><div data-world-reveal><span>VISION</span><h2>Every enterprise grows intelligence it owns.</h2><p>A future where company-specific AI compounds inside the organization as a durable asset, improving work while remaining accountable to people.</p></div><div className="company-values">{["Evidence before theatre","Human judgment stays consequential","Sovereignty by architecture","Learning must be measurable"].map((x,i)=><span key={x}>0{i+1} · {x}</span>)}</div></section><section className="company-history"><div><p>THE HISTORY</p><h2>Built from delivery.<br/><em>Not a lab demo.</em></h2></div><div>{history.map(x=><article key={x.year} data-world-reveal><strong>{x.year}</strong><h3>{x.title}</h3><p>{x.body}</p></article>)}</div></section><section className="company-team"><div><p>LEADERSHIP & DELIVERY</p><h2>The people behind<br/><em>the perimeter.</em></h2><span>Operators, architects, researchers, and builders across the United States, United Arab Emirates, and India.</span></div><div className="company-team-grid">{leaders.map(l=><article key={l.name} data-world-reveal><span>{l.initials}</span><small>{l.role}</small><h3>{l.name}</h3><p>{l.bio}</p></article>)}</div></section><section className="company-cred"><article><strong>300–400%</strong><span>company-reported year-on-year revenue growth</span></article><article><strong>DIFC</strong><span>Dubai entity registered under an AI license at DIFC AI Campus</span></article><article><strong>2025 · 2026</strong><span>back-to-back Times Health Award recognition reported by Neurologic AI</span></article><article><strong>US · UAE · INDIA</strong><span>company, market, and engineering operating footprint</span></article></section></>}

function DecisionSignature({id}:{id:string}){
  if(id==="deployment")return <section className="deployment-blueprints" id="experience"><div><p>THREE BLUEPRINTS</p><h2>Choose the boundary.<br/><em>Keep the ownership.</em></h2></div>{[{n:"01",title:"Customer cloud",detail:"Your account · VPC/VNet · keys · registry · telemetry",flow:["SSO","APP","MODEL","GPU"]},{n:"02",title:"Dedicated private",detail:"Single tenant · private connectivity · selected region",flow:["IDP","PRIVATE LINK","RUNTIME","KMS"]},{n:"03",title:"Air-gapped on-prem",detail:"Offline installer · secure media · local marketplace",flow:["DIRECTORY","APP","LOCAL MODEL","LOCAL GPU"]}].map(x=><article key={x.title} data-world-reveal><span>{x.n}</span><h3>{x.title}</h3><p>{x.detail}</p><div>{x.flow.map(y=><b key={y}>{y}</b>)}</div><small>NO REQUIRED VENDOR DATA PATH</small></article>)}</section>;
  if(id==="security")return <section className="security-ledger" id="experience"><div><p>THE SECURITY DOSSIER</p><h2>A request, traced<br/><em>through every control.</em></h2></div><div className="ledger-path">{[{n:"01",title:"Identity",body:"SSO, directory groups, role, document policy."},{n:"02",title:"Data",body:"Customer keys, retrieval boundary, source permissions."},{n:"03",title:"Model",body:"Routing policy, guardrails, redaction, action scopes."},{n:"04",title:"Evidence",body:"Sources, response, tool calls, approvals, outcome."},{n:"05",title:"Learning",body:"Separate permission, provenance, evaluation, rollback."}].map(x=><article key={x.title} data-world-reveal><span>{x.n}</span><h3>{x.title}</h3><p>{x.body}</p><i>EVENT LOGGED</i></article>)}</div><p className="security-note">Control implementation is deployment-specific. Certification status, penetration testing, RTO/RPO, and formal mappings belong in the security pack—not in decorative badges.</p></section>;
  if(id==="pricing")return <section className="pricing-model" id="experience"><div><p>THE COMMERCIAL MODEL</p><h2>Pay for the platform.<br/><em>Grow adoption freely.</em></h2></div><div className="pricing-steps"><article><span>01 · PILOT</span><h3>90-day working proof</h3><p>Agreed workflows, deployment boundary, success criteria, and evidence plan on your data and infrastructure.</p><b>MOST FEE CREDITED ON CONVERSION</b></article><article><span>02 · LICENSE</span><h3>Flat enterprise tier</h3><p>All five pillars, included SDKs, marketplace, and the agreed deployment shape—without a per-user penalty.</p><b>PRICE SHARED IN WRITING</b></article><article><span>03 · CADENCE</span><h3>Quarterly compounding</h3><p>Optimization, adapter refresh, evaluation, memory hygiene, and a proof-of-learning review.</p><b>ASSUMPTIONS ATTACHED</b></article></div><div className="pricing-compare"><span>OWNED</span><b>INFRASTRUCTURE</b><b>WEIGHTS + ADAPTERS</b><b>MEMORY + EMBEDDINGS</b><b>SKILLS + AGENTS</b><i>NO PER-SEAT METER</i></div></section>;
  if(id==="partners")return <section className="partner-system" id="experience"><div className="partner-programs"><article><strong>AWS</strong><span>ACTIVATE PROGRAM</span><p>Startup program acceptance as reported by Neurologic AI.</p></article><article><strong>NVIDIA</strong><span>CONNECT PROGRAM</span><p>Program participation status as reported by Neurologic AI; not represented here as a product certification.</p></article></div><div className="partner-motions">{[{n:"01",title:"OEM",body:"Your brand and accounts, with Corporate GPT embedded as the sovereign AI platform."},{n:"02",title:"Co-sell",body:"Joint discovery, architecture, pilot, and delivery with explicit account and support ownership."},{n:"03",title:"Internal first",body:"Deploy inside the partner, build the reference, then take the operating model to customers."}].map(x=><article key={x.title}><span>{x.n}</span><h3>{x.title}</h3><p>{x.body}</p><i>ENABLE → DELIVER → RENEW</i></article>)}</div></section>;
  if(id==="resources")return <section className="resource-library" id="experience"><div><p>THE LIBRARY</p><h2>Fewer pieces.<br/><em>More signal.</em></h2></div><div className="resource-grid">{[{type:"BRIEFING",title:"Corporate GPT product & architecture deck",meta:"Available in a working session",status:"AVAILABLE"},{type:"DEMO",title:"Enterprise search, agents, and governed work",meta:"Product walkthrough",status:"AVAILABLE IN BRIEFING"},{type:"RESEARCH",title:"The Gauntlet Report",meta:"Why enterprise AI pilots die in review",status:"IN PREPARATION"},{type:"FIELD MODEL",title:"Owned vs. rented intelligence",meta:"Five-year TCO and asset framework",status:"BRIEFING EDITION"},{type:"SECURITY",title:"Governing the learning layer",meta:"Provenance, evaluation, rollback, unlearning",status:"IN PREPARATION"},{type:"WORKSHOP",title:"Sovereign AI Bootcamp",meta:"One day · your data · your infrastructure",status:"BY APPLICATION"}].map((x,i)=><article key={x.title} data-world-reveal><span>0{i+1} · {x.type}</span><h3>{x.title}</h3><p>{x.meta}</p><b>{x.status}</b></article>)}</div></section>;
  return null;
}

const legalSections:Record<string,{title:string;body:string}[]>={
  "legal/privacy":[{title:"Who controls the data",body:"Neurologic AI is the controller for information submitted through this website. Customer deployments are governed by the applicable customer agreement and deployment architecture."},{title:"What this website handles",body:"Information you choose to provide in a briefing request, basic security and reliability logs, and communications required to respond. This site does not use third-party advertising pixels or sell visitor data."},{title:"Why and how long",body:"Submission data is used to respond, prepare the requested session, prevent abuse, and keep required business records. Retention is limited to those purposes and applicable legal obligations."},{title:"Where processing occurs",body:"Neurologic AI operates across the United States, United Arab Emirates, and India. Appropriate contractual and technical safeguards apply where information crosses jurisdictions."},{title:"Your choices",body:"You may request access, correction, deletion, restriction, or a copy of information, subject to applicable law and necessary legal retention. Contact privacy@neurologicai.com."},{title:"Cookies and operational logs",body:"Only necessary site functionality and privacy-respecting operational logging should be enabled. Any future analytics or cookie use must be reflected here before activation."}],
  "legal/terms":[{title:"Use of this website",body:"You may use the site to evaluate Neurologic AI and Corporate GPT. Do not interfere with service operation, attempt unauthorized access, or misuse content or marks."},{title:"Information, not a contract",body:"Website content is general information. Product scope, service levels, security commitments, pricing, and customer outcomes are governed by signed agreements."},{title:"Intellectual property",body:"Content, product names, design, and Neurologic AI marks remain the property of Neurologic AI or their respective owners. Reasonable internal evaluation is welcome."},{title:"Third-party names and marks",body:"Customer and partner names are used only to describe approved relationships or program status. Their marks remain the property of their owners."},{title:"Availability and liability",body:"The website is provided as available. To the extent permitted by law, Neurologic AI disclaims implied warranties and liability beyond what cannot lawfully be excluded."},{title:"Changes and contact",body:"Terms may be updated as the site and applicable law evolve. Material changes should receive a revised effective date. Formal questions: legal@neurologicai.com."}],
  "legal/subprocessors":[{title:"Website hosting",body:"Infrastructure serving this website and its static assets may process limited operational logs. The provider legal name, location, and change date must be published before production launch."},{title:"Business communications",body:"The business email provider may process briefing-request communications. No form endpoint is represented as active until it is actually connected."},{title:"Customer deployments",body:"Customer-managed cloud and air-gapped deployments can eliminate vendor-side content subprocessors. The applicable list is specific to the deployment and stated contractually."},{title:"Change notice",body:"A production subprocessor register should include provider, purpose, location, data categories, optionality, safeguards, and an effective date, plus a subscription path for changes."}],
};
function LegalDocument({id,page}:{id:string;page:PageContent}){const sections=legalSections[id];return <><WorldHero id={id} page={page} compact/><section className="legal-document"><aside><span>DOCUMENT STATUS</span><b>WORKING WEBSITE NOTICE</b><small>Effective 13 July 2026<br/>Final counsel review required before launch.</small><nav>{sections.map((x,i)=><a href={`#legal-${i+1}`} key={x.title}>{String(i+1).padStart(2,"0")} {x.title}</a>)}</nav></aside><article>{sections.map((x,i)=><section id={`legal-${i+1}`} key={x.title}><span>{String(i+1).padStart(2,"0")}</span><h2>{x.title}</h2><p>{x.body}</p></section>)}<div className="legal-contact"><h2>Plain-language questions deserve a human answer.</h2><a href="mailto:legal@neurologicai.com">legal@neurologicai.com ↗</a></div></article></section></>}

function WorldCTA({page,id}:{page:PageContent;id:string}){return <section className="world-cta"><span>{id.replaceAll("/"," · ").toUpperCase()}</span><h2>{page.cta}</h2>{page.ctaBody&&<p>{page.ctaBody}</p>}<div><Link href="/briefing">Book a sovereignty briefing ↗</Link><Link href="/proof">Inspect customer proof</Link></div></section>}

export function WorldPage({id,page}:{id:string;page:PageContent}){
  if(id.startsWith("legal/"))return <div className="world-page document-world"><WorldMotion/><SiteHeader/><main id="main"><SectionNav id="security"/><LegalDocument id={id} page={page}/></main><SiteFooter/></div>;
  const isPillar=id.startsWith("platform/");
  return <div className={`world-page route-${id.replaceAll("/","-")}`}><WorldMotion/><SiteHeader/><main id="main"><SectionNav id={id}/><WorldHero id={id} page={page}/>{id==="platform"&&<AeiSystemFilm/>}{isPillar&&<JourneyFilm id={id}/>} {id==="proof"&&<ProofLibrary/>}{id==="company"&&<CompanyStory/>}{id==="industries"&&<IndustriesIndex/>}{id.startsWith("industries/")&&<IndustryStory id={id}/>} {["deployment","security","pricing","partners","resources"].includes(id)&&<DecisionSignature id={id}/>} {(id==="platform"||isPillar||["deployment","security","pricing","partners"].includes(id))&&<ContentAtlas page={page}/>}<WorldCTA page={page} id={id}/></main><SiteFooter/></div>
}
