export type ContentBlock = {
  label?: string;
  title: string;
  body?: string;
  items?: { title: string; body: string; metric?: string }[];
  note?: string;
  visual?: "curve" | "loop" | "gates" | "timeline" | "pillars" | "tiers";
};

export type PageContent = {
  title: string;
  description: string;
  label?: string;
  hero: string;
  intro: string;
  accent?: "proof" | "paper";
  stats?: { value: string; label: string }[];
  blocks: ContentBlock[];
  cta: string;
  ctaBody?: string;
};

export const pages: Record<string, PageContent> = {
  platform: {
    title: "Platform — Three levels, five shared capabilities", description: "AI Assistants, Governed Agents, and Digital Experts powered by KNOW, WORK, LEARN, BUILD, and TRUST.", label: "The platform", hero: "One stack. Three levels of enterprise intelligence.", intro: "AI Assistants ground company knowledge for every employee. Governed Agents execute repeatable work across systems and approvals. Digital Experts scale scarce expertise through specialist tools and held-out evaluation. All three inherit one enterprise context, one model policy, one authority model, and one evaluation system.",
    blocks: [
      { label: "THE THREE LEVELS", title: "Activate usefulness, action, and expertise on one foundation.", items: [{ title: "AI Assistants · Live product", body: "Ground company knowledge and carry everyday analysis forward for every employee." }, { title: "Governed Agents · Activation deliverable", body: "Execute bounded, repeatable work across systems and human approval points." }, { title: "Digital Experts · Method proven + activation", body: "Scale scarce expertise through specialist tools, held-out evaluation, and governed release." }] },
      { label: "FIVE SHARED CAPABILITIES", title: "Five pillars behave like one operating system.", body: "KNOW grounds the work. WORK carries it forward. LEARN improves accepted capability. BUILD makes it reusable. TRUST governs what every person and system may see, do, learn, and release.", visual: "pillars" },
      { label: "CLOSED ENTERPRISE SYSTEM", title: "One architecture from enterprise identity to accepted outcome.", items: [{title:"Identity & context",body:"Enterprise identity, policy, knowledge, data, and semantic context."},{title:"Models & execution",body:"Policy-routed models, governed agents, workflows, specialist tools, and simulators."},{title:"Evaluation & release",body:"Held-out evaluation, human authorization, versioned release, monitoring, and rollback."}], note: "APPROVED SIGNAL → CANDIDATE → EVALUATE → AUTHORIZE → RELEASE → OBSERVE → IMPROVE OR ROLL BACK" }
    ], cta: "Define the first three accepted outcomes."
  },
  "platform/know": {
    title: "KNOW — Grounded enterprise answers", description: "Permission-aware retrieval with source attribution, evidence review, and visible refusal paths.", label: "PILLAR 01 — THE KNOWLEDGE ENGINE", hero: "Every grounded answer shows its sources.", intro: "KNOW investigates permissioned enterprise sources, makes the evidence set visible, and can refuse when the available material is insufficient. Quality is measured on a customer-approved evaluation set.",
    blocks: [
      { label: "AGENTIC RETRIEVAL", title: "It doesn’t search. It investigates.", body: "Ask a project-status question and an agent decomposes it, pulls tickets, plans, chat threads, transcripts, and documents—then reconciles them into one cited answer." },
      { label: "TWO-STAGE VALIDATION", title: "Inspect the evidence before accepting the answer.", items: [{ title: "Discover & validate", body: "The system shows the sources it found and where they came from. The permitted review model is configured for the workflow." }, { title: "Generate & attribute", body: "Grounded-answer mode attaches source passages and can refuse when evidence is insufficient; results remain subject to human review where policy requires." }], note: "CONFIDENCE CONTROLS · VERBATIM MODE · VISIBLE ‘I DON’T KNOW’ PATH" },
      { label: "70+ CONNECTOR CATALOG", title: "Permission-aware to the source.", body: "Microsoft 365, Google Workspace, ERP, CRM, service desks, files, databases, APIs, and approved web sources can join one governed layer. Exact connector availability, read/write scope, refresh behavior, and boundary compatibility are confirmed per proposal." },
      { label: "KNOWLEDGE GRAPH", title: "It also knows who knows.", body: "An entity graph across documents, people, and concepts powers multi-hop answers and a permission-aware Expert Finder—answered from evidence, not org charts." },
      { label: "THE COMPOUNDING", title: "Retrieval that improves weekly.", body: "KNOW learns which sources are canonical, which are stale, and which retrieval strategies work for which questions—on your corpus, not someone else’s benchmark." }
    ], cta: "Bring a question your current tools can’t answer."
  },
  "platform/work": {
    title: "WORK — The AI coworker", description: "Quick answers, deep persistent sessions, packaged skills, and no-code workflows.", label: "PILLAR 02 — THE AI COWORKER", hero: "It doesn’t chat about the work. It does the work.", intro: "WORK opens files, analyzes data, drafts the document, builds the model, and carries multi-step tasks to done—with your team in the loop and every action attributed and logged.",
    blocks: [
      { label: "QUICK MODE", title: "The everyday co-pilot. First words in under a second.", body: "Summarize, compare, translate, flag conflicts; draft and edit documents, spreadsheets, and presentations into ready-to-use outputs." },
      { label: "DEEP MODE", title: "Workspaces for work that takes days, not prompts.", body: "A sandboxed session holds files, data, tool state, teammates, and artifacts across the engagement. A code interpreter performs real analysis; every step is logged with attribution." },
      { label: "SKILLS ENGINE", title: "Packaged expertise, not blank prompts.", items: [{title:"Financial analysis",body:"Models, variance narratives, and board-ready outputs."},{title:"Compliance review",body:"Policy-shaped review with evidence and exception handling."},{title:"Research synthesis",body:"Multi-source investigation with a defensible source trail."}] },
      { label: "WORKFLOW BUILDER", title: "Automate recurring work. No code, full control.", body: "Trigger → steps → approval gates → deploy. Durable execution with retries, versioning, rollback, and human sign-off wherever you demand it." },
      { label: "ADAPTIVE WORKSPACES", title: "A workspace that learns the job.", body: "Role workspaces adapt from observed usage. The system promotes what each role repeatedly needs—the difference between software with settings and a colleague who learns." }
    ], cta: "Pick a deliverable. Watch it get made."
  },
  "platform/learn": {
    title: "LEARN — Capability that earns every release", description: "Customer-specific memory, retrieval, procedures, evaluation, and approved specialization inside the enterprise boundary.", label: "PILLAR 03 — THE LEARNING CORE", hero: "Capability compounds. Every release earns acceptance.", intro: "Corporate GPT can improve memory in minutes, retrieval and procedures over weeks, and approved specialist capability per release. Nothing self-promotes: every candidate is evaluated on agreed work, authorized by a person, and kept reversible.", accent: "proof",
    blocks: [
      { label: "THE CLOSED LOOP", title: "Approved work becomes candidate capability.", body: "Accepted signals are curated with permission and provenance. Candidates are compared with the deployed baseline on an agreed held-out set; regressions do not ship. Where contracted, customer-specific adapters can be trained inside the customer boundary.", visual: "loop", note: "AIR-GAPPED CONFIGURATIONS SUPPORT A SIGNED OFFLINE UPDATE AND EVALUATION PATH." },
      { label: "FIVE DEPTHS", title: "It learns at five depths.", items: [{title:"Vocabulary",body:"Your acronyms, products, and document idioms."},{title:"Systems",body:"Your tools, APIs, and reliable action paths."},{title:"Domain",body:"Your industry’s language and reasoning patterns."},{title:"Judgment",body:"Your format, tone, depth, and risk posture."},{title:"Craft",body:"Procedural competence at a specific job."}] },
      { label: "COGNITIVE MEMORY", title: "It remembers like an organization, not a chat log.", items: [{title:"Individual",body:"Preferences, projects, and decisions—visible and correctable."},{title:"Departmental",body:"Team conventions and workflows inherited on day one."},{title:"Enterprise",body:"Canonical facts, policy, precedent, and the memo behind it."}] },
      { label: "ROADMAP UNLESS CONTRACTED", title: "Repeated work can become a governed capability proposal.", body: "Where explicitly included, the system can surface repeated patterns and draft an agent proposal. Every proposal still requires an owner, capability manifest, least-privilege scopes, evaluation, and human approval." },
      { label: "THE PROOF", title: "Show the candidate against the baseline.", body: "Task accuracy, retrieval quality, correct abstention, expert acceptance, time-to-output, and cost per accepted outcome are measured on representative customer work. The customer defines the production threshold.", visual: "curve" },
      { label: "CUSTOMER-SPECIFIC INTELLIGENCE", title: "Learning stays specific to the customer boundary.", body: "Customer-specific retrieval, memory, evaluation sets, configurations, and adapters can improve inside the agreed environment. Ownership and license rights for base models, platform IP, and customer-created assets follow their respective licenses and the signed customer agreement." }
    ], cta: "Ask every AI vendor one question: ‘Show me my learning curve.’", ctaBody: "We can. Bring that question to a briefing."
  },
  "platform/build": {
    title: "BUILD — Your organizational AI layer", description: "Four SDKs, an internal marketplace, governed agents, and drop-in inference.", label: "PILLAR 04 — THE DEVELOPER PLATFORM", hero: "Every team builds. The whole company benefits.", intro: "Any internal application gets governed search, validated retrieval, agents, and model inference through one API—so no team rebuilds RAG, security, or governance again.",
    blocks: [
      { label: "FOUR SDKs", title: "Everything your platform team needs. Nothing it should rebuild.", items: [{title:"Skill SDK",body:"Versioned expertise with golden-case tests and marketplace publishing."},{title:"Agent SDK",body:"Tools, memory, sandboxed multi-step execution, and complete audit."},{title:"Connector SDK",body:"Proprietary sources with uniform schemas and access controls."},{title:"Widget SDK",body:"Embed cited search, chat, and dashboards in any internal app."}] },
      { label: "ROADMAP UNLESS CONTRACTED", title: "Capability proposals can start from repeated work.", body: "Where explicitly included, roles, direct requests, and repeated behavior can trigger a draft agent proposal. Every draft arrives with a capability manifest and least-privilege scopes for human review." },
      { label: "ROADMAP UNLESS CONTRACTED · AI ADMINISTRATOR", title: "Platform operations can be proposed, never silently promoted.", body: "A governed administrative agent may propose retrieval tuning, connectors, recurring skills, and evaluation runs. Any availability, scope, and release authority is explicit in the contracted capability matrix." },
      { label: "API & MARKETPLACE", title: "One API for search, skills, agents, workflows, and inference.", body: "A private marketplace catalogs every approved capability—ratings, security status, one-click install, and rollback. Air-gapped deployments run their own instance." }
    ], cta: "Bring your platform team. This briefing is for them."
  },
  "platform/trust": {
    title: "TRUST — The AI compliance signs off on", description: "Document-level permissions, immutable audit, layered guardrails, and governed learning.", label: "PILLAR 05 — THE GOVERNANCE LAYER", hero: "The AI your compliance officer signs off on.", intro: "TRUST governs the three things most vendors govern zero of: your data, the AI’s actions, and what the models learn.",
    blocks: [
      { label: "THE GAUNTLET", title: "Four gates. One deployable architecture.", visual: "gates", items: [{title:"Access",body:"If a person can’t see it, their AI can’t either."},{title:"Guardrails",body:"Policy, scanning, anonymization, and citation-only mode."},{title:"Audit",body:"Every interaction written to an append-only, hash-chained store."},{title:"Learning",body:"Provenance, permissioned training, evaluation, and unlearning."}] },
      { label: "GATE 01 — ACCESS", title: "Permissions enforced to the document, at query time.", body: "SSO, directory sync, role-based access, customer-managed encryption keys. Unauthorized content never appears in results, answers, memory, or training data." },
      { label: "GATE 02 — GUARDRAILS", title: "Three layers between users and mistakes.", body: "Policy enforcement, input/output scanning, and a pre-model anonymization layer—with per-category controls your DPO owns." },
      { label: "GATE 03 — AUDIT", title: "Every interaction, immutably logged.", body: "Query, response, sources, actions, model, cost, and session. Sub-second search, SIEM export, and retention to your policy." },
      { label: "GATE 04 — GOVERNED LEARNING", title: "Govern what an AI may learn.", body: "Approved adapter candidates retain provenance to the training set. Evaluation gates can block regressions. Retraction and deletion procedures cover indexes, memory, training sets, and—where technically applicable—adapter remediation or replacement." },
      { label: "MODEL CONTROL", title: "You hold the keys. And the kill switch.", body: "A model registry, routing policies, canary rollout, real-time cost, and a platform-wide kill switch in under 30 seconds with automatic fallback." }
    ], cta: "Bring your hardest security question.", ctaBody: "Bring your CISO too. This is the meeting we’re best at."
  },
  deployment: {
    title: "Deployment — Choose the enterprise boundary", description: "Customer-managed cloud, private infrastructure, and air-gapped deployment paths with explicit data, model, support, update, and integration boundaries.", label: "Deployment & sovereignty", hero: "Choose the boundary that matches the work.", intro: "Every proposed path is explicit about data, models, telemetry, support, updates, and integrations. Parity is never assumed across boundaries; the exact configuration is validated before activation.",
    blocks: [
      { label: "THREE VALIDATED SHAPES", title: "Sovereignty in the form the workload requires.", items: [{title:"Customer-managed cloud",body:"Customer account and approved services, with local, managed, or policy-routed frontier models and connected, controlled updates."},{title:"Private data centre or private cloud",body:"Customer-hosted models and approved private endpoints on customer infrastructure, with private or staged updates."},{title:"Air-gapped environment",body:"Local models, no required external data path, and signed offline bundles for sovereign or disconnected work."}] },
      { label: "FORWARD-DEPLOYED DELIVERY", title: "Engineers sit alongside the real work.", items: [{title:"Observe",body:"Map the workflow, decision owners, systems, and evidence standard where the work happens."},{title:"Build",body:"Implement and evaluate inside the agreed boundary with named customer and Neurologic owners."},{title:"Transfer",body:"Train the customer team to operate and extend accepted capability without creating dependence."}] },
      { label: "ACCEPTANCE CLOCK", title: "Every date is an acceptance test, not a promise.", visual: "timeline", items: [{title:"Day 30 · Architecture",body:"Boundary, data paths, owners, baselines, and evaluation sets accepted."},{title:"Day 60 · Candidates",body:"First assistant groups and bounded workflows reviewed by the people who own the work."},{title:"Day 90 · Evidence",body:"First contracted outcome accepted, remedied, or rejected against the signed standard."},{title:"Months 4–12 · Expand",body:"Promote accepted capability across teams and expert domains."}] },
      { label: "PRODUCTION REFERENCE", title: "A lead deployment reached production in 12 weeks.", body: "That timing is customer-reported evidence from one production deployment—not an unconditional promise. Contracted milestones, dependencies, customer responsibilities, and acceptance evidence govern every activation." }
    ], cta: "Choose the boundary and define the first acceptance test."
  },
  security: {
    title: "Security — One authority chain from evidence to release", description: "Identity, source authority, evidence, model and tool policy, human approval, audit, evaluation, release, monitoring, and rollback.", label: "Security & governance", hero: "Capability can increase. Authority never moves by itself.", intro: "Corporate GPT applies one authority chain from identity and source access through evidence, model policy, tool scope, human approval, audit, evaluation, versioned release, monitoring, and rollback.",
    blocks: [
      { label: "THE AUTHORITY CHAIN", title: "One chain governs the complete lifecycle.", items: [{title:"Identity & source authority",body:"Enterprise identities, service identities, permissions, and source ownership resolve before retrieval or action."},{title:"Evidence & policy",body:"Material claims, model routing, tool scope, and permitted data paths remain explicit for the task."},{title:"Human authority",body:"Consequential actions and capability promotion pause for the named decision owner."},{title:"Audit & evaluation",body:"Events are attributable and candidates are compared against agreed baseline and held-out work."},{title:"Release & monitoring",body:"Signed versions, operational monitoring, revocation, and rollback close the chain."}] },
      { label: "GOVERNED AGENT CONTROLS", title: "Built for failure, not only the happy path.", items: [{title:"Scoped identity",body:"Least privilege for people, services, data, and tools."},{title:"Exceptions & recovery",body:"Idempotency, retries, failure handling, and recovery paths are designed per workflow."},{title:"Approval & revocation",body:"Human gates, kill switches, revocation, and replay remain available to accountable operators."},{title:"Audit",body:"Tool calls, evidence, approvals, outcomes, and failures can be reconstructed."}] },
      { label: "AIR-GAPPED CONFIGURATION", title: "No required external data path.", body: "In the air-gapped configuration, local models, customer infrastructure, and signed offline update bundles allow operation without a required external path. Support, updates, integrations, and telemetry are documented for the exact deployment." },
      { label: "READINESS, NOT CERTIFICATION", title: "Controls mapped for review. Certifications named only when earned.", body: "SOC 2, HIPAA, GDPR, and EU AI Act control families can be mapped in the security pack. This describes readiness and configuration-specific controls—not certification, legal advice, or universal applicability." },
      { label: "CLAIMS WE DO NOT MAKE", title: "Measurements are engineering. Absolutes are marketing.", body: "No ‘zero hallucinations.’ Grounded-answer mode attributes evidence and can refuse, with quality measured on the agreed evaluation set. No universal zero-egress claim across connected configurations. No compliance seals we have not earned." }
    ], cta: "Bring your security questionnaire to the briefing."
  },
  industries: {
    title: "Industries — Built for data that can’t leave", description: "Five industry operating models with explicit workflow, risk, deployment, and evidence status.", label: "Industry operating models", hero: "One platform. Five operating realities.", intro: "Healthcare, semiconductor, government, manufacturing, and retail each begin with a different boundary, workflow, approval chain, and proof standard. The platform stays coherent; the operating model does not pretend to be generic.", accent: "paper",
    blocks: [{ label: "FOUR WEDGES", title: "Where constraint becomes competitive advantage.", items: [{title:"Healthcare & med devices",body:"Compliance-first AI at customer-reported 5,000-user on-prem production scale."},{title:"Manufacturing & industrial",body:"Institutional knowledge made cited and available across shifts."},{title:"Retail & hospitality",body:"Multilingual service intelligence inside the agreed infrastructure boundary."},{title:"Semiconductor",body:"Air-gap-capable intelligence where IP is the entire company."}] }], cta: "Show us the workflow your current AI can’t touch."
  },
  "industries/healthcare": {
    title: "Healthcare & med devices — Designed for regulated review", description: "Globus Medical production evidence: 5,000 users, fully on-premises, controlled evidence, and retained human review.", label: "HEALTHCARE & MEDICAL DEVICES · PRODUCTION", hero: "The first question is not what AI can do. It is what regulated review requires.", intro: "The approved Globus Medical production story begins with controlled knowledge, document-level permissions, cited outputs, customer-controlled infrastructure, and human judgment that remains consequential. Sensitive workflow detail is intentionally withheld.", stats:[{value:"5,000",label:"reported production users"},{value:"On-prem",label:"customer-hosted"},{value:"4–5×",label:"reported review acceleration"}],
    blocks: [{label:"REGULATED WORK",title:"Research and review accelerated with evidence.",items:[{title:"Evidence-bound research",body:"Permitted technical and business records assembled with their source trail intact."},{title:"Regulated review",body:"Controlled documents and procedures investigated with visible evidence and refusal paths."},{title:"Expert enablement",body:"Cited answers support specialists without displacing consequential judgment."},{title:"Human decision",body:"The accountable reviewer retains sign-off and a reconstructable record."}]},{label:"EVIDENCE NOTE",title:"Scale and acceleration are customer-reported.",body:"The 5,000-user scale, fully on-premises deployment, 4–5× review acceleration, and 12-week production timing are customer-reported. Measurement detail belongs in the evidence pack."}], cta:"Bring the review workflow your current AI cannot enter."
  },
  "industries/government": {
    title:"Government & public sector — Cited sovereign AI",description:"Dubai CommerCity production evidence: official-source guidance for founders in the UAE.",label:"GOVERNMENT & PUBLIC SECTOR · PRODUCTION",hero:"Public answers should survive public scrutiny.",intro:"At Dubai CommerCity, a production service grounds founder guidance in approved regulations and program information, remains available around the clock, and routes exceptions to the appropriate human channel.",stats:[{value:"PRODUCTION",label:"customer status"},{value:"24/7",label:"reported service availability"},{value:"5–6×",label:"reported onboarding speed"}],blocks:[{label:"PUBLIC SERVICE FLOW",title:"From question to an official-source answer.",items:[{title:"Public question",body:"A founder asks in natural language without learning an institutional taxonomy."},{title:"Approved corpus",body:"Retrieval is constrained to current approved regulations, programs, and public guidance."},{title:"Cited response",body:"Material statements point back to the supporting source passage."},{title:"Human escalation",body:"Sensitive or unresolved questions route to the appropriate institutional channel."}]},{label:"EVIDENCE NOTE",title:"Availability and acceleration are customer-reported.",body:"The 24/7 service availability and 5–6× company-onboarding acceleration are customer-reported and should not be read as an independently audited productivity study."}],cta:"Bring the public-service question that must never be improvised."
  },
  "industries/manufacturing": {
    title: "Manufacturing — Capture tribal knowledge", description: "A solution playbook for plant, product, maintenance, supplier, and expert knowledge.", label:"MANUFACTURING · SOLUTION PLAYBOOK", hero:"Your best engineer will retire. Their operating judgment does not have to.", intro:"Connect the plant’s formal record with the tolerances, supplier quirks, and night-shift fixes that live only in people—without pretending a solution playbook is named production proof.",
    blocks:[{label:"SOLUTION PATTERNS",title:"Institutional memory, moved from hallway to system.",items:[{title:"Tribal knowledge",body:"SOPs, maintenance logs, and engineering changes made searchable with their source context."},{title:"Product structure",body:"Cross-reference product, component, and change records with every line traceable."},{title:"Troubleshooting",body:"Investigate likely causes against approved machine history and operating records."},{title:"Supplier quality",body:"Reconcile certificates, non-conformances, and audit records across permitted systems."}]},{label:"WHERE IT RUNS",title:"On the plant network if that is where it has to live.",body:"Air-gapped is a supported configuration, with the exact offline model, update, connector, and evaluation path confirmed in the proposal."}], cta:"Bring your hardest institutional-memory problem."
  },
  "industries/retail": {
    title:"Retail & hospitality — Service intelligence",description:"Three status-labeled operational field experiences across voice, multilingual guidance, and product assistance.",label:"RETAIL & HOSPITALITY · FIELD EXPERIENCES",hero:"The best service agent is present at the exact moment of need.",intro:"Voice, multilingual guidance, and product-assistance experiences across three operational settings—described at a pattern level so customer and workflow detail remains appropriately masked.",
    blocks:[{label:"SOLUTION PATTERNS",title:"Better service at the moment of the question.",items:[{title:"Frontline expert",body:"Product, availability, and policy answers in the customer’s language."},{title:"Inventory-aware concierge",body:"Recommendations that respect permitted availability and business rules."},{title:"Merchandising intelligence",body:"Cited analysis across approved sales, stock, and promotion records."},{title:"Staff operations",body:"Procedures, policy, and standards available across shifts."}]},{label:"WHY THE BOUNDARY MATTERS",title:"Service intelligence contains competitive operating knowledge.",body:"Customer data, pricing strategy, supplier terms, and merchandising methods remain governed by the signed deployment and asset-rights agreement."}],cta:"Choose one service moment and define the evidence."
  },
  "industries/semiconductor": {
    title:"Semiconductor — AI where IP is the company",description:"Micron paid method proof: specialist engineering optimization evaluated on held-out work inside a controlled engagement.",label:"SEMICONDUCTOR · PAID METHOD PROOF",hero:"When IP is the company, the boundary is part of the product.",intro:"For Micron, a specialist engineering-optimization method was evaluated on held-out work inside a paid, controlled engagement. The benchmark result is approved for public disclosure; the exact operational workflow remains intentionally masked. This is not presented as a production deployment.",
    blocks:[{label:"HELD-OUT EVALUATION",title:"A specialist method won 7 of 10 held-out cases.",items:[{title:"Result",body:"70% win rate: seven wins to three, with no ties."},{title:"Efficiency",body:"Median three versus seven simulation steps—57% fewer median steps."},{title:"Scope",body:"Ten held-out cases and 146 optimization targets against a GPT-5.5-based baseline."},{title:"Bridge",body:"Specialist method, tool loop, held-out evaluation, and governed release form the Digital Expert pattern."}]},{label:"EVIDENCE NOTE",title:"Method proof is not production proof.",body:"Scope is held exactly: a paid specialist engineering engagement, not a Corporate GPT production deployment. Customer-confidential operational detail is withheld."}],cta:"Bring the specialist method that must earn its release."
  },
  proof: {
    title:"Proof — Production evidence and measured method",description:"Production outcomes, paid method proof, and an anonymized production result—each labeled by scope, source, and maturity.",label:"Customers & evidence",hero:"Evidence and product maturity are different claims.",intro:"Production, live product, paid method proof, activation deliverable, and roadmap describe different things. Every case below states its scope, method, status, and evidence source.",stats:[{value:"5,000",label:"reported users on-prem"},{value:"2",label:"named production deployments"},{value:"1",label:"paid method proof"}],
    blocks:[{label:"PRODUCTION · ON-PREMISES",title:"5,000 users. Evidence-bound research under human review.",body:"Globus Medical operates a customer-controlled production deployment. The 4–5× acceleration and 12-week timing are customer-reported."},{label:"PRODUCTION · UAE",title:"Official-source founder guidance, available around the clock.",body:"Dubai CommerCity reports 24/7 service availability and 5–6× faster company onboarding."},{label:"PAID METHOD PROOF",title:"A specialist method won 7 of 10 held-out cases.",body:"Micron engagement results: 70% win rate and 57% fewer median simulation steps. Exact operational detail is masked; production status is not implied."},{label:"ANONYMIZED PRODUCTION OUTCOME",title:"Several weeks of senior analysis, completed in three hours.",body:"A governed research agent reconciled permitted enterprise records and returned an evidence-backed analysis. The customer, business function, transaction context, and exact issue are intentionally withheld."}],cta:"Request the evidence pack."
  },
  pricing: {
    title:"Commercial model — Activate in stages, accept on evidence",description:"One agreement across three intelligence levels, staged workstreams, a governed capacity envelope, and outcome-specific acceptance evidence.",label:"Commercial model",hero:"Sign once. Activate in stages. Accept only on evidence.",intro:"One platform agreement can cover AI Assistants, Governed Agents, and Digital Experts across the agreed environments and capacity envelope. Each workstream activates against its own baseline, owner, milestones, dependencies, and acceptance evidence.",
    blocks:[{label:"ONE AGREEMENT · THREE WORKSTREAMS",title:"Clear ownership from purchase to accepted outcome.",items:[{title:"What you buy",body:"One platform agreement across the three intelligence levels, agreed environments, defined capacity envelope, support, and contractually defined ownership and portability."},{title:"How it activates",body:"Assistant, Governed Agent, and Digital Expert workstreams run in parallel, each with a named owner, milestones, dependencies, and evidence."},{title:"How you are protected",body:"Every workstream carries a baseline, acceptance test, remedy, and change control in the contract."}]},{label:"OWNED CAPACITY",title:"Meterless internal usage within contracted capacity.",body:"Capacity, routing, frontier escalation, infrastructure, support, and external spend caps remain explicit. Success becomes higher utilization—not an unbounded usage bill."},{label:"ACCEPTED-OUTCOME ECONOMICS",title:"Cost per accepted outcome is the controlling metric.",body:"Infrastructure, committed capacity, platform, external models, capability build, evaluation, human intervention, operations, and support belong in one economic model.",note:"FORECAST COST · RECONCILE ACTUALS · GOVERN VARIANCE"},{label:"ASSET RIGHTS",title:"The contract defines what the enterprise controls.",body:"Source connections, permission mappings, indexes, configurations, evaluation sets, accepted baselines, workflows, tools, skills, agent definitions, approved work traces, adapters, and release evidence are governed by the signed agreement."}],cta:"Model the first three accepted outcomes."
  },
  integrations: {
    title:"Integrations — 70+ governed enterprise connectors",description:"A catalog of 70+ connector patterns for Microsoft 365, Google Workspace, ERP, CRM, service desks, files, data, web, MCP, and internal tools.",label:"Integrations",hero:"Plugs into everything you already run.",intro:"A catalog of 70+ enterprise connectors brings permitted knowledge and approved actions into one governed layer. Every connector inherits enterprise identity, permissions, policy, and audit.",
    blocks:[{label:"CONNECTOR CATALOG",title:"The systems where enterprise work already lives.",items:[{title:"Microsoft 365",body:"Outlook, Teams, SharePoint, and OneDrive patterns."},{title:"Google Workspace",body:"Gmail, Drive, Docs, and Calendar patterns."},{title:"ERP & finance",body:"Approved systems of record and governed finance workflows."},{title:"CRM",body:"Customer, service, and pipeline systems."},{title:"Service desks",body:"ITSM, operations, and support queues."},{title:"Files, data & web",body:"File systems, warehouses, databases, APIs, and approved web search."}]},{label:"MODEL CONTEXT PROTOCOL",title:"Internal and proprietary tools join through one governed layer.",body:"MCP can connect internal applications and specialist tools without bypassing identity, permissions, approval, or audit.",note:"READ AND ACT · WITHIN POLICY"},{label:"SCOPE NOTE",title:"Catalog breadth is not universal deployment availability.",body:"Exact connector availability, authentication method, read/write scope, refresh behavior, action support, and compatibility with customer cloud, private, or air-gapped configurations are confirmed against the customer stack in the proposal."}],cta:"Map the first systems and data paths."
  },
  partners: {
    title:"Partners — Build a practice that compounds",description:"AWS Activate, NVIDIA Connect, and three delivery motions for systems integrators and infrastructure partners.",label:"Partner ecosystem",hero:"Your relationships. Your infrastructure. A platform that compounds.",intro:"Neurologic AI reports acceptance into the AWS Activate program and participation in NVIDIA Connect. Around that ecosystem, partners can OEM, co-sell, or deploy internally first—with delivery ownership made explicit.",
    blocks:[{label:"THREE MOTIONS",title:"Choose how we go to market together.",items:[{title:"OEM",body:"Embed under your brand—a sovereign AI offer without years of platform R&D."},{title:"Co-sell",body:"Your delivery strength and relationships; our platform and production proof."},{title:"Internal",body:"Deploy for your own organization first—the reference that shortens every later conversation."}]},{label:"WHO",title:"Built for the sovereign AI ecosystem.",body:"Systems integrators, hardware vendors, national AI programs, regional ecosystems, and cloud providers. We do not compete with national models; we put them to work."},{label:"WHAT PARTNERS GET",title:"An installed base that becomes easier to renew.",body:"Reference architectures, validated designs, joint pilot economics, industry packs, enablement, demo environments, and per-customer proof-of-learning dashboards."}],cta:"Building a sovereign AI practice? Let’s scope the first account."
  },
  company: {
    title:"Company — The Neurologic AI team behind Corporate GPT",description:"A 22-person engineering and delivery team spanning models, evaluation, product, platform, security, deployment, and customer outcomes.",label:"A NEUROLOGIC AI PRODUCT",hero:"The people who sell the vision remain visible in delivery.",intro:"A 22-person engineering and delivery team spans models, evaluation, product, platform, security, deployment, and customer outcomes across the United States, UAE, and India. Every production workstream carries a named owner.",accent:"paper",
    blocks:[{label:"THE BELIEF",title:"Intelligence about your company should belong to your company.",body:"Every enterprise will run on AI. The question is whether that intelligence accumulates inside the enterprise as a governed asset—or inside a vendor as a metered service."},{label:"LEADERSHIP",title:"Built by operators, architects, and researchers.",items:[{title:"Nishan Ali · Founder & CEO",body:"Twelve years in applied AI and enterprise transformation; formerly UnitedHealth Group."},{title:"John Gillotte · Co-Founder & CTO",body:"Twenty-two years building production technology at scale, including early engineering experience at AWS S3 and Microsoft Research."},{title:"Dr. Santanu Das · Chairman",body:"Fifty-two years in technology; founder of TranSwitch Corporation, which reached NASDAQ."}]},{label:"NAMED RESPONSIBILITY",title:"Every customer sees the assigned people.",body:"Executive sponsorship, architecture, model specialization, security, deployment reliability, customer outcomes, and Digital Expert acceptance each receive named ownership in the proposal."},{label:"PUBLIC BENCHMARKS",title:"Foundation-model depth, measured publicly.",body:"Neurologic AI reports that its radiology foundation system outperformed public Google and Microsoft baselines. This claim should be relied on only alongside the benchmark record: datasets, versions, scores, protocol, date, and report or code."}],cta:"Meet the team that answers its own briefings."
  },
  resources: {
    title:"Resources — Product, research, and field work",description:"A small, status-labeled library of product material, research in preparation, security notes, and hands-on workshops.",label:"Resources",hero:"Fewer pieces. More signal.",intro:"Available material is labeled available. Work in preparation is labeled in preparation. No invented download library, no dead report links, and no content-farm filler.",accent:"paper",
    blocks:[{label:"SOVEREIGN AI BOOTCAMP",title:"One day. Your data. Your infrastructure. Working AI by evening.",body:"Connect a real corpus, stand up validated retrieval, run a skill on actual work, and leave with an architecture memo. For teams who evaluate by building, not watching demos."},{label:"CISO ROUNDTABLES",title:"Peers and practitioners. Off the record.",body:"Small sessions on AI governance, shadow-AI reality, and learning-layer security—under Chatham House rules."},{label:"QUARTERLY RESEARCH",title:"Three reports for the launch library.",items:[{title:"The Gauntlet Report",body:"Why enterprise AI pilots die in review—and the architecture of those that survive."},{title:"Owned vs. Rented Intelligence",body:"A five-year TCO and asset-value framework."},{title:"Governing the Learning Layer",body:"Provenance, evaluation gates, and machine unlearning for the CISO."}]},{label:"FIELD NOTES",title:"Written by the people who built it.",body:"What air-gapped learning requires, how retrieval is evaluated on customer corpora, and what document-level permissions cost at query time."}],cta:"Attend a Sovereign AI Bootcamp."
  },
  "legal/privacy": {title:"Privacy — Plain language",description:"How Neurologic AI handles website visitor data.",label:"Legal & trust",hero:"Privacy should be readable.",intro:"This website does not use third-party advertising pixels, sell visitor data, or follow you around the internet.",accent:"paper",blocks:[{label:"WHAT WE COLLECT",title:"Only what is needed to respond.",body:"If you submit a briefing request, we collect the information you provide so a human can reply. Basic privacy-respecting operational logs may be retained for security and reliability."},{label:"HOW WE USE IT",title:"One purpose. No resale.",body:"We use submitted information to respond to your request, prepare the requested session, and maintain necessary business records. We do not sell it."},{label:"YOUR CHOICES",title:"Access, correction, and deletion.",body:"Contact privacy@neurologicai.com to request access, correction, or deletion, subject to applicable legal retention obligations."}],cta:"Questions about privacy? Ask us directly."},
  "legal/terms": {title:"Terms — Website use",description:"Terms governing use of the Corporate GPT website.",label:"Legal & trust",hero:"Terms, without theatre.",intro:"This site provides general information about Neurologic AI and Corporate GPT. Product commitments belong in signed agreements, not browser tabs.",accent:"paper",blocks:[{label:"INFORMATION",title:"Accurate, but not a contract.",body:"We work to keep published information accurate. Modeled figures are identified as modeled; customer claims may be anonymized or subject to public-name approval."},{label:"INTELLECTUAL PROPERTY",title:"Our materials remain ours.",body:"Site content, design, and marks are owned by Neurologic AI or their respective licensors. Reasonable internal evaluation use is welcome."},{label:"CONTACT",title:"A human answers legal questions.",body:"Write to legal@neurologicai.com for formal notices or questions."}],cta:"Need contractual detail? Put it on the briefing agenda."},
  "legal/subprocessors": {title:"Subprocessors — Short on purpose",description:"The short list of providers supporting this website.",label:"Legal & trust",hero:"This list is short on purpose.",intro:"The product is designed to run inside the customer perimeter. Customer deployment subprocessors depend on the deployment model and are documented contractually.",accent:"paper",blocks:[{label:"WEBSITE",title:"Infrastructure, kept minimal.",items:[{title:"Hosting infrastructure",body:"Serves this website and its static assets."},{title:"Business email",body:"Routes briefing requests to the team when submission infrastructure is enabled."}]},{label:"PRODUCT DEPLOYMENTS",title:"Your environment determines the list.",body:"Customer-managed and air-gapped deployments can eliminate vendor-side data subprocessors entirely. The applicable list is stated in each customer agreement."}],cta:"Ask for the subprocessor architecture for your deployment."
  }
};
