export type ContentBlock = {
  label?: string;
  title: string;
  body?: string;
  items?: { title: string; body: string; metric?: string }[];
  note?: string;
  visual?: "curve" | "loop" | "gates" | "timeline" | "pillars" | "tiers";
};

export type PageContent = {
  title: string;
  description: string;
  label?: string;
  hero: string;
  intro: string;
  accent?: "proof" | "paper";
  stats?: { value: string; label: string }[];
  blocks: ContentBlock[];
  cta: string;
  ctaBody?: string;
};

export const pages: Record<string, PageContent> = {
  platform: {
    title: "Platform — Five pillars, one AI operating system", description: "KNOW, WORK, LEARN, BUILD, TRUST — one data layer, one security model, one experience.", label: "The platform", hero: "Not another tool. Your AI operating system.", intro: "A knowledge engine that proves its answers, a coworker that ships real work, a learning core that compounds, a developer platform that spreads capability, and a governance layer that makes all of it deployable.",
    blocks: [
      { label: "ONE SYSTEM", title: "Five pillars that behave like one product.", body: "An answer retrieved by KNOW feeds a WORK session. Its patterns feed LEARN. LEARN proposes an agent that BUILD assembles. TRUST governs every step—including what models may learn and what they must provably forget.", visual: "pillars" },
      { label: "THE ARCHITECTURE", title: "Each pillar is complete. Together, they compound.", items: [
        { title: "KNOW", body: "Validated, permission-aware retrieval. Every claim cited or refused." }, { title: "WORK", body: "Persistent cowork sessions that carry real deliverables to done." }, { title: "LEARN", body: "Sovereign fine-tuning and organizational memory, measured on your tasks." }, { title: "BUILD", body: "Four SDKs and an internal marketplace for reusable enterprise capability." }, { title: "TRUST", body: "Access, audit, guardrails, provenance, evaluation, and unlearning." }] },
      { label: "TWO-MODEL RUNTIME", title: "Two models. No sprawl. Every deployment.", body: "A dense model for user-facing quality and a mixture-of-experts model for agent speed, behind one routing layer with per-customer adapters. When better open models ship, your learned adapters come along.", note: "MULTI-LLM CONTROL PLANE · HOT-SWAPPABLE ADAPTERS · KILL SWITCH <30S" }
    ], cta: "See all five pillars in one 45-minute briefing."
  },
  "platform/know": {
    title: "KNOW — Every claim cited or refused", description: "Agentic retrieval across 50+ enterprise systems with two-stage validation.", label: "PILLAR 01 — THE KNOWLEDGE ENGINE", hero: "Every answer has a source.", intro: "KNOW retrieves like an analyst rather than a search box, and refuses to state what it cannot cite. It is the difference between an AI your teams quote in meetings and one they double-check afterward.",
    blocks: [
      { label: "AGENTIC RETRIEVAL", title: "It doesn’t search. It investigates.", body: "Ask a project-status question and an agent decomposes it, pulls tickets, plans, chat threads, transcripts, and documents—then reconciles them into one cited answer." },
      { label: "TWO-STAGE VALIDATION", title: "You see the sources before the AI writes a word.", items: [{ title: "Discover & validate", body: "The system shows everything it found and where it came from. You choose which sources it may use." }, { title: "Generate & cite", body: "Only validated sources feed the answer. Every claim links to a passage; unsupported answers are refused." }], note: "CONFIDENCE DIAL · VERBATIM MODE · GRACEFUL ‘I DON’T KNOW’" },
      { label: "50+ CONNECTORS", title: "Permission-aware to the document.", body: "Documents, conversations, project tools, meetings, databases, and APIs. Access controls are enforced at query time and refreshed continuously. If a person cannot open the document, their AI never reveals it." },
      { label: "KNOWLEDGE GRAPH", title: "It also knows who knows.", body: "An entity graph across documents, people, and concepts powers multi-hop answers and a permission-aware Expert Finder—answered from evidence, not org charts." },
      { label: "THE COMPOUNDING", title: "Retrieval that improves weekly.", body: "KNOW learns which sources are canonical, which are stale, and which retrieval strategies work for which questions—on your corpus, not someone else’s benchmark." }
    ], cta: "Bring a question your current tools can’t answer."
  },
  "platform/work": {
    title: "WORK — The AI coworker", description: "Quick answers, deep persistent sessions, packaged skills, and no-code workflows.", label: "PILLAR 02 — THE AI COWORKER", hero: "It doesn’t chat about the work. It does the work.", intro: "WORK opens files, analyzes data, drafts the document, builds the model, and carries multi-step tasks to done—with your team in the loop and every action attributed and logged.",
    blocks: [
      { label: "QUICK MODE", title: "The everyday co-pilot. First words in under a second.", body: "Summarize, compare, translate, flag conflicts; draft and edit documents, spreadsheets, and presentations into ready-to-use outputs." },
      { label: "DEEP MODE", title: "Workspaces for work that takes days, not prompts.", body: "A sandboxed session holds files, data, tool state, teammates, and artifacts across the engagement. A code interpreter performs real analysis; every step is logged with attribution." },
      { label: "SKILLS ENGINE", title: "Packaged expertise, not blank prompts.", items: [{title:"Financial analysis",body:"Models, variance narratives, and board-ready outputs."},{title:"Compliance review",body:"Policy-shaped review with evidence and exception handling."},{title:"Research synthesis",body:"Multi-source investigation with a defensible source trail."}] },
      { label: "WORKFLOW BUILDER", title: "Automate recurring work. No code, full control.", body: "Trigger → steps → approval gates → deploy. Durable execution with retries, versioning, rollback, and human sign-off wherever you demand it." },
      { label: "ADAPTIVE WORKSPACES", title: "A workspace that learns the job.", body: "Role workspaces adapt from observed usage. The system promotes what each role repeatedly needs—the difference between software with settings and a colleague who learns." }
    ], cta: "Pick a deliverable. Watch it get made."
  },
  "platform/learn": {
    title: "LEARN — Smarter every quarter, provably", description: "A sovereign learning engine with fine-tuning, organizational memory, and proof-of-learning.", label: "PILLAR 03 — THE LEARNING CORE", hero: "Smarter every week. Provably.", intro: "Everything else on this site, someone will eventually imitate. This is the pillar they can’t: Corporate GPT learns your company at the level of model weights, inside your own perimeter—and shows you the curve.", accent: "proof",
    blocks: [
      { label: "THE CLOSED LOOP", title: "A learning loop that never leaves your walls.", body: "Usage signal becomes curated training data. Fine-tuning runs on your GPUs. Every candidate is evaluated against your gold-standard set; nothing that regresses ships. Adapters hot-swap with zero downtime and instant rollback.", visual: "loop", note: "NO EXTERNAL CONNECTIVITY REQUIRED. THE LOOP RUNS AIR-GAPPED." },
      { label: "FIVE DEPTHS", title: "It learns at five depths.", items: [{title:"Vocabulary",body:"Your acronyms, products, and document idioms."},{title:"Systems",body:"Your tools, APIs, and reliable action paths."},{title:"Domain",body:"Your industry’s language and reasoning patterns."},{title:"Judgment",body:"Your format, tone, depth, and risk posture."},{title:"Craft",body:"Procedural competence at a specific job."}] },
      { label: "COGNITIVE MEMORY", title: "It remembers like an organization, not a chat log.", items: [{title:"Individual",body:"Preferences, projects, and decisions—visible and correctable."},{title:"Departmental",body:"Team conventions and workflows inherited on day one."},{title:"Enterprise",body:"Canonical facts, policy, precedent, and the memo behind it."}] },
      { label: "PROCESS INTELLIGENCE", title: "It notices the work you repeat—and offers to take it.", body: "The system surfaces bottlenecks and repeated patterns, then proposes agents as drafts. Proposals, never surprises: every generated agent goes through review and approval." },
      { label: "THE PROOF", title: "“Your assistant improved 14% on your tasks this quarter—here’s the dashboard.”", body: "Task accuracy, retrieval quality, acceptance rates, and time-to-output—measured on your work and reviewed with you every quarter. We don’t ask you to believe the learning. We show you the slope.", visual: "curve" },
      { label: "OWNED INTELLIGENCE", title: "A multi-tenant product cannot learn your company. Structurally.", body: "A shared model must stay identical for every tenant. Ours becomes one of one. After a year, the model is your institutional memory, encoded in weights you own." }
    ], cta: "Ask every AI vendor one question: ‘Show me my learning curve.’", ctaBody: "We can. Bring that question to a briefing."
  },
  "platform/build": {
    title: "BUILD — Your organizational AI layer", description: "Four SDKs, an internal marketplace, governed agents, and drop-in inference.", label: "PILLAR 04 — THE DEVELOPER PLATFORM", hero: "Every team builds. The whole company benefits.", intro: "Any internal application gets governed search, validated retrieval, agents, and model inference through one API—so no team rebuilds RAG, security, or governance again.",
    blocks: [
      { label: "FOUR SDKs", title: "Everything your platform team needs. Nothing it should rebuild.", items: [{title:"Skill SDK",body:"Versioned expertise with golden-case tests and marketplace publishing."},{title:"Agent SDK",body:"Tools, memory, sandboxed multi-step execution, and complete audit."},{title:"Connector SDK",body:"Proprietary sources with uniform schemas and access controls."},{title:"Widget SDK",body:"Embed cited search, chat, and dashboards in any internal app."}] },
      { label: "SELF-PROPOSING AGENTS", title: "The platform notices what to build next.", body: "Roles, direct requests, and repeated behavior can trigger an agent proposal. Every draft arrives with a capability manifest and least-privilege scopes for human review." },
      { label: "AI ADMINISTRATOR", title: "The platform maintains the platform.", body: "A governed meta-agent tunes retrieval, proposes connectors, drafts recurring skills, schedules learning runs, and reports what it changed and why." },
      { label: "API & MARKETPLACE", title: "One API for search, skills, agents, workflows, and inference.", body: "A private marketplace catalogs every approved capability—ratings, security status, one-click install, and rollback. Air-gapped deployments run their own instance." }
    ], cta: "Bring your platform team. This briefing is for them."
  },
  "platform/trust": {
    title: "TRUST — The AI compliance signs off on", description: "Document-level permissions, immutable audit, layered guardrails, and governed learning.", label: "PILLAR 05 — THE GOVERNANCE LAYER", hero: "The AI your compliance officer signs off on.", intro: "TRUST governs the three things most vendors govern zero of: your data, the AI’s actions, and what the models learn.",
    blocks: [
      { label: "THE GAUNTLET", title: "Four gates. One deployable architecture.", visual: "gates", items: [{title:"Access",body:"If a person can’t see it, their AI can’t either."},{title:"Guardrails",body:"Policy, scanning, anonymization, and citation-only mode."},{title:"Audit",body:"Every interaction written to an append-only, hash-chained store."},{title:"Learning",body:"Provenance, permissioned training, evaluation, and unlearning."}] },
      { label: "GATE 01 — ACCESS", title: "Permissions enforced to the document, at query time.", body: "SSO, directory sync, role-based access, customer-managed encryption keys. Unauthorized content never appears in results, answers, memory, or training data." },
      { label: "GATE 02 — GUARDRAILS", title: "Three layers between users and mistakes.", body: "Policy enforcement, input/output scanning, and a pre-model anonymization layer—with per-category controls your DPO owns." },
      { label: "GATE 03 — AUDIT", title: "Every interaction, immutably logged.", body: "Query, response, sources, actions, model, cost, and session. Sub-second search, SIEM export, and retention to your policy." },
      { label: "GATE 04 — GOVERNED LEARNING", title: "The first governance layer for what an AI learns.", body: "Every adapter is traceable to its training data. Evaluation gates block regressions. Retracted knowledge is verifiably forgotten from index, memory, and weights." },
      { label: "MODEL CONTROL", title: "You hold the keys. And the kill switch.", body: "A model registry, routing policies, canary rollout, real-time cost, and a platform-wide kill switch in under 30 seconds with automatic fallback." }
    ], cta: "Bring your hardest security question.", ctaBody: "Bring your CISO too. This is the meeting we’re best at."
  },
  deployment: {
    title: "Deployment — Your infrastructure", description: "Customer cloud, private cloud, or fully offline. Live in 12 weeks.", label: "Deployment & sovereignty", hero: "Your intelligence. Your infrastructure. Period.", intro: "Corporate GPT runs where your data already lives. Models included, weights included, learning included. Nothing calls home—there is no home to call.",
    blocks: [
      { label: "THREE OPTIONS", title: "Sovereignty in the shape your environment requires.", items: [{title:"Customer-managed cloud",body:"Full deployment into your cloud account. Your account, keys, network, and provisioning code."},{title:"Dedicated private cloud",body:"Fully isolated single tenancy, private connectivity, your region and keys."},{title:"Air-gapped on-prem",body:"Offline installer, local marketplace, secure-media updates, and learning without internet."}] },
      { label: "SIZING", title: "From one department to the whole enterprise.", visual: "tiers", body: "Reference architectures exist for every tier. At smaller tiers, adapter training uses existing inference hardware in off-peak windows." },
      { label: "HONEST ECONOMICS", title: "Sovereignty costs single-digit percent more to run. And it’s the only option that appreciates.", body: "At 500 users, self-hosted infrastructure models within roughly 6–8% of the most aggressive serverless alternative. Sovereignty is a rounding error on infrastructure—and a moat on value.", note: "MODELED — NEUROLOGIC AI ENGINEERING COST MODEL, 2026" },
      { label: "THE RAIL", title: "Live in 12 weeks. Learning from week one.", visual: "timeline", items: [{title:"Weeks 1–3 · Connect",body:"Infrastructure, SSO, permissions, priority connectors, guardrails, and pilot users."},{title:"Weeks 4–8 · Activate",body:"Skills, validated retrieval, workflows, first fine-tune, and proof readout."},{title:"Weeks 9–12 · Scale",body:"Department expansion, custom capabilities, memory, and control-plane handover."},{title:"Every quarter",body:"Adapter refresh, optimization, memory hygiene, and proof-of-learning review."}] }
    ], cta: "Tell us your constraints. We’ve deployed under harder ones."
  },
  security: {
    title: "Security & compliance — Built for the gauntlet", description: "Zero egress, customer-managed keys, immutable audit, and verifiable unlearning.", label: "Security & compliance", hero: "Written for the people whose job is to say no.", intro: "The platform runs in your perimeter, honors permissions at query time and training time, logs everything immutably, and can verifiably forget.",
    blocks: [
      { label: "POSTURE AT A GLANCE", title: "Architecture, not adjectives.", items: [{title:"Data egress",body:"None. Models, indexes, weights, and telemetry remain in your environment."},{title:"Encryption",body:"Customer-managed keys; encrypted at rest and in transit."},{title:"Identity",body:"SSO, directory sync, RBAC, and document-level enforcement."},{title:"Audit",body:"Append-only, hash-chained logs with SIEM export."},{title:"Learning",body:"Permission-aware training, signed adapters, gates, and unlearning."},{title:"Model control",body:"Registry, routing, canary rollout, kill switch under 30 seconds."}] },
      { label: "CLAIMS WE DON’T MAKE", title: "Measurements are engineering. Absolutes are marketing.", body: "No ‘zero hallucinations.’ We say every claim cited or refused, with error rates measured on your evaluation set. No unsourced statistics. No compliance seals we haven’t earned." },
      { label: "SENSITIVE DATA", title: "Redaction before the model. Policies you set.", body: "Prompts and retrieved content are masked before any model sees them. Per-category policy—mask, tokenize, or block—is controlled by your data-protection team." },
      { label: "YOUR QUESTIONNAIRE", title: "We answer with architecture diagrams.", body: "Request the security architecture pack, compliance control mappings, and the unlearning demonstration—or send your questionnaire and we’ll return it completed." }
    ], cta: "Bring your security questionnaire to the briefing."
  },
  industries: {
    title: "Industries — Built for data that can’t leave", description: "Five industry operating models with explicit workflow, risk, deployment, and evidence status.", label: "Industry operating models", hero: "One platform. Five operating realities.", intro: "Healthcare, semiconductor, government, manufacturing, and retail each begin with a different boundary, workflow, approval chain, and proof standard. The platform stays coherent; the operating model does not pretend to be generic.", accent: "paper",
    blocks: [{ label: "FOUR WEDGES", title: "Where constraint becomes competitive advantage.", items: [{title:"Healthcare & med devices",body:"Compliance-first AI in production at 5,000-user on-prem scale."},{title:"Manufacturing & industrial",body:"Thirty years of tribal knowledge, cited and available on every shift."},{title:"Retail & hospitality",body:"Multilingual service intelligence on infrastructure you own."},{title:"Semiconductor",body:"Air-gap-capable intelligence where IP is the entire company."}] }], cta: "Show us the workflow your current AI can’t touch."
  },
  "industries/healthcare": {
    title: "Healthcare & med devices — AI that passes compliance", description: "Globus Medical production story: 5,000 users, fully on-premises, with controlled evidence and human review.", label: "HEALTHCARE & MEDICAL DEVICES · PRODUCTION", hero: "The first question is not what AI can do. It is what Compliance will approve.", intro: "At Globus Medical, the production story begins with controlled documents, document-level permissions, cited outputs, customer-owned infrastructure, and human judgment that remains consequential.", stats:[{value:"5,000",label:"users in production"},{value:"On-prem",label:"customer-hosted"},{value:"4–5×",label:"reported review acceleration"}],
    blocks: [{label:"DAY-ONE WORKFLOWS",title:"Regulated work, accelerated with evidence.",items:[{title:"Surgical case prep",body:"Device docs, technique guides, and relevant prior cases assembled and cited.",metric:"HOURS → MINUTES"},{title:"Regulatory intelligence",body:"Submissions, standards, and SOPs in quote-only mode.",metric:"REVIEW TIME −75%¹"},{title:"Quality & CAPA",body:"Investigations grounded in device history and complaint files.",metric:"AUDIT PREP −50%¹"},{title:"Clinical enablement",body:"Cited answers about indications and instrumentation.",metric:"TIME-TO-ANSWER −80%¹"}]},{label:"THE PACK",title:"Packaged learning, not just packaged content.",body:"A regulatory-shaped skill set, priority connectors, HIPAA-mapped controls with BAA, and validation-friendly documentation."}], cta:"Your compliance team has questions. Good. Ours has answers."
  },
  "industries/government": {
    title:"Government & public sector — Cited sovereign AI",description:"Dubai CommerCity public-live story: official-source guidance deployed for founders in the UAE.",label:"GOVERNMENT & PUBLIC SECTOR · PUBLIC-LIVE",hero:"Public answers should survive public scrutiny.",intro:"At Dubai CommerCity, founder guidance is grounded in official regulations and available around the clock. The answer path remains visible—from public question to approved source to cited response.",stats:[{value:"LIVE",label:"public deployment"},{value:"24/7",label:"service availability"},{value:"UAE",label:"in-region story"}],blocks:[{label:"PUBLIC SERVICE FLOW",title:"From question to an official-source answer.",items:[{title:"Public question",body:"A founder asks in natural language without learning an institutional taxonomy."},{title:"Approved corpus",body:"Retrieval is constrained to current official regulations, programs, and public guidance."},{title:"Cited response",body:"Material statements point back to the supporting source passage."},{title:"Human escalation",body:"Sensitive or unresolved questions route to the appropriate institutional channel."}]},{label:"SOVEREIGN DELIVERY",title:"In-region architecture with an accountable content path.",body:"Content approval, source freshness, audit, language status, and escalation are operational responsibilities—not decorative claims."}],cta:"Bring the public-service question that must never be improvised."
  },
  "industries/manufacturing": {
    title: "Manufacturing — Capture tribal knowledge", description: "A solution playbook for plant, product, maintenance, supplier, and expert knowledge.", label:"MANUFACTURING · SOLUTION PLAYBOOK", hero:"Your best engineer will retire. Their operating judgment does not have to.", intro:"Connect the plant’s formal record with the tolerances, supplier quirks, and night-shift fixes that live only in people—without pretending a solution playbook is named production proof.",
    blocks:[{label:"USE CASES",title:"Institutional memory, moved from hallway to system.",items:[{title:"Tribal knowledge",body:"SOPs, maintenance logs, and engineering changes—searchable and permanent.",metric:"ONBOARDING −50%¹"},{title:"BOM assistant",body:"Hours of cross-referencing reduced to minutes, with every line traceable.",metric:"HOURS → MINUTES"},{title:"Troubleshooting",body:"Likely causes grounded in your machine history, not a generic manual.",metric:"MTTR ↓"},{title:"Supplier quality",body:"Certificates, non-conformances, and audits reconciled across systems.",metric:"AUDIT PREP −50%¹"}]},{label:"WHERE IT RUNS",title:"On the plant network if that’s where it has to live.",body:"Air-gapped is a supported deployment, not an exception—and the offline learning loop still compounds."}], cta:"Bring your worst tribal-knowledge story."
  },
  "industries/retail": {
    title:"Retail & hospitality — Service intelligence",description:"Drive-through voice, Thailand mall assistance, duty-free concierge, and frontline operations intelligence.",label:"RETAIL & HOSPITALITY · THREE FIELD EXPERIENCES",hero:"The best service agent is present at the exact moment of need.",intro:"A voice agent at the drive-through. A multilingual guide across a Thailand mall. A product concierge at a major Thailand duty-free operator. Three very different service realities, designed as operational systems rather than generic chatbots.",
    blocks:[{label:"USE CASES",title:"Better service at the moment of the question.",items:[{title:"In-aisle expert",body:"Product, stock, and policy answers in the customer’s language.",metric:"BASKET +8–12%¹"},{title:"Inventory-aware concierge",body:"Recommendations that respect real-time availability."},{title:"Merchandising intelligence",body:"Cited analysis across sales, stock, and promo calendars."},{title:"Staff operations",body:"Procedures, policy, and standards in one place, every shift."}]},{label:"WHY SOVEREIGNTY",title:"Merchandising instinct is a competitive weapon.",body:"Rented AI means teaching a shared system with your customer data, pricing strategy, and supplier terms. Owned AI keeps those instincts yours."}],cta:"Pilot it on one flagship floor. Measure the basket."
  },
  "industries/semiconductor": {
    title:"Semiconductor — AI where IP is the company",description:"Micron paid-POC story: an autonomous engineering loop inside a controlled boundary.",label:"SEMICONDUCTOR · PAID PROOF OF CONCEPT",hero:"When IP is the company, the boundary is part of the product.",intro:"For Micron, the public story is deliberately precise: a paid proof of concept for an engineering loop that can simulate, review, revise, and re-run inside the agreed environment.",
    blocks:[{label:"USE CASES",title:"The leverage engineers need, in the posture security demands.",items:[{title:"PDK navigator",body:"Cited answers across design kits, internal specs, and errata.",metric:"SEARCH 35% → 85%¹"},{title:"Process & yield",body:"Decades of notes and reports reconciled and sourced."},{title:"Tape-out support",body:"Checklists, precedent, and prior-issue retrieval in verbatim mode."},{title:"Engineer ramp",body:"Five-year-veteran knowledge available in week one."}]},{label:"CREDIBILITY",title:"We know why your security team starts with ‘no.’",body:"Our chairman took a semiconductor company from founding to NASDAQ. We know what it takes to earn the ‘yes.’"}],cta:"Air-gapped means air-gapped. Come test the claim."
  },
  proof: {
    title:"Proof — Named deployments and evidence status",description:"Micron, Globus Medical, Dubai CommerCity, Skan AI, and three operational agent experiences—with every engagement labeled by status.",label:"Customers & proof",hero:"Evidence is only useful when its status is clear.",intro:"Production, public-live, paid POC, client collaboration, and customer-confidential field work are not interchangeable. This page makes the deployment shape, approved scope, and evidence note visible for every story.",stats:[{value:"5,000",label:"users on-prem"},{value:"4",label:"named relationships"},{value:"3",label:"field experiences"}],
    blocks:[{label:"HEALTHCARE · ON-PREM · TIER XL",title:"5,000 users. On-premises. Twelve weeks to production.",body:"A top-5 NYSE-listed spine implant manufacturer runs the platform on its own infrastructure under FDA-, HIPAA-, and SOX-grade scrutiny. KNOW, WORK, and TRUST are live; the first per-customer learning curve is being measured."},{label:"GCC · SOVEREIGN CLOUD",title:"Sovereignty sells beyond regulation.",body:"A UAE economic-zone deployment brings cited public Q&A and a digital advisor to thousands of pages of official content—in-region, with Arabic on the roadmap."},{label:"SEMICONDUCTOR · PAID POC",title:"The hardest industry to sell AI into is evaluating ours. For pay.",body:"A paid proof-of-concept is underway in an industry where IP protection is existential. We publish no details beyond that—which is exactly the discretion the industry demands."},{label:"THE STANDARD",title:"Every customer gets a curve.",body:"From week one, each deployment builds a gold-standard evaluation set. Every quarter we review accuracy, retrieval quality, acceptance, and time-to-output.",visual:"curve"}],cta:"Ask us what the curves actually look like."
  },
  pricing: {
    title:"Pricing — Flat enterprise licensing",description:"No per-seat meter. Flat enterprise licensing and value that compounds.",label:"The ownership model",hero:"Per-seat pricing punishes success. Ours rewards it.",intro:"Adoption costs nothing extra, and everything the platform learns accrues to you.",
    blocks:[{label:"HOW IT WORKS",title:"Clear at the first meeting. Structured for ownership.",items:[{title:"The pilot",body:"A structured 90-day pilot on your data and infrastructure, with agreed success criteria and most of the fee credited on production conversion."},{title:"The license",body:"One flat enterprise license by deployment tier—covering all five pillars, included skills, SDKs, and marketplace."},{title:"The cadence",body:"Quarterly adapter refresh, optimization, and proof-of-learning review—the rhythm that manufactures the curve."}]},{label:"NEVER IN THE MODEL",title:"No meter. No query anxiety. No pricing surprises.",body:"No paying rent on your own institutional knowledge. Numbers are shared in the first briefing, in writing, with assumptions attached."},{label:"THE ASSET",title:"The only AI line item that appreciates.",body:"At four-figure user counts, flat licensing models millions below per-seat alternatives—before counting the embeddings, memory, adapters, and agents you own.",note:"MODELED — NEUROLOGIC AI TCO ANALYSIS, 2026"}],cta:"Get the numbers. In writing. In the first meeting."
  },
  partners: {
    title:"Partners — Build a practice that compounds",description:"AWS Activate, NVIDIA Connect, and three delivery motions for systems integrators and infrastructure partners.",label:"Partner ecosystem",hero:"Your relationships. Your infrastructure. A platform that compounds.",intro:"Neurologic AI reports acceptance into the AWS Activate program and participation in NVIDIA Connect. Around that ecosystem, partners can OEM, co-sell, or deploy internally first—with delivery ownership made explicit.",
    blocks:[{label:"THREE MOTIONS",title:"Choose how we go to market together.",items:[{title:"OEM",body:"Embed under your brand—a sovereign AI offer without years of platform R&D."},{title:"Co-sell",body:"Your delivery strength and relationships; our platform and production proof."},{title:"Internal",body:"Deploy for your own organization first—the reference that shortens every later conversation."}]},{label:"WHO",title:"Built for the sovereign AI ecosystem.",body:"Systems integrators, hardware vendors, national AI programs, regional ecosystems, and cloud providers. We do not compete with national models; we put them to work."},{label:"WHAT PARTNERS GET",title:"An installed base that becomes easier to renew.",body:"Reference architectures, validated designs, joint pilot economics, industry packs, enablement, demo environments, and per-customer proof-of-learning dashboards."}],cta:"Building a sovereign AI practice? Let’s scope the first account."
  },
  company: {
    title:"Company — Neurologic AI",description:"Mission, vision, history, leadership, global footprint, growth, and recognition behind Corporate GPT.",label:"A NEUROLOGIC AI PRODUCT",hero:"We build the AI enterprises are allowed to own.",intro:"Neurologic AI combines production delivery, enterprise architecture, foundation-model research, regulated-industry depth, and a US–UAE–India operating shape. Corporate GPT is the product expression of that company.",accent:"paper",
    blocks:[{label:"THE BELIEF",title:"Intelligence about your company should belong to your company.",body:"Every enterprise will run on AI. The question is whether that intelligence accumulates inside the enterprise as an asset it owns—or inside a vendor, as a service it rents."},{label:"LEADERSHIP",title:"Built by operators, architects, and researchers.",items:[{title:"Nishan Ali · CEO",body:"M.Tech in AI, IIT Jodhpur; formerly UnitedHealth Group. Leads the company and every customer’s first briefing."},{title:"Dr. Santanu Das · Chairman",body:"Took TranSwitch Corporation from founding to NASDAQ; author of the Adaptive Enterprise Intelligence architecture."},{title:"John Gillotte · CTO",body:"22 years in enterprise technology; foundation-model and healthcare imaging architecture."},{title:"Alfaz Ahmed · Engineering Lead",body:"Formerly Amazon and Siemens; leads engineering across the US and India."}]},{label:"HOW WE WORK",title:"The website practices what the product preaches.",body:"Every statistic carries its source. Every projection is a range and says so. No tracking pixels follow you after you leave. If we govern our marketing this carefully, imagine the audit log."},{label:"CAREERS",title:"‘Runs air-gapped’ is a design constraint worth loving.",body:"We hire engineers who agree. Write to careers@neurologicai.com."}],cta:"Meet the team that answers its own briefings."
  },
  resources: {
    title:"Resources — Product, research, and field work",description:"A small, status-labeled library of product material, research in preparation, security notes, and hands-on workshops.",label:"Resources",hero:"Fewer pieces. More signal.",intro:"Available material is labeled available. Work in preparation is labeled in preparation. No invented download library, no dead report links, and no content-farm filler.",accent:"paper",
    blocks:[{label:"SOVEREIGN AI BOOTCAMP",title:"One day. Your data. Your infrastructure. Working AI by evening.",body:"Connect a real corpus, stand up validated retrieval, run a skill on actual work, and leave with an architecture memo. For teams who evaluate by building, not watching demos."},{label:"CISO ROUNDTABLES",title:"Peers and practitioners. Off the record.",body:"Small sessions on AI governance, shadow-AI reality, and learning-layer security—under Chatham House rules."},{label:"QUARTERLY RESEARCH",title:"Three reports for the launch library.",items:[{title:"The Gauntlet Report",body:"Why enterprise AI pilots die in review—and the architecture of those that survive."},{title:"Owned vs. Rented Intelligence",body:"A five-year TCO and asset-value framework."},{title:"Governing the Learning Layer",body:"Provenance, evaluation gates, and machine unlearning for the CISO."}]},{label:"FIELD NOTES",title:"Written by the people who built it.",body:"What air-gapped learning requires, how retrieval is evaluated on customer corpora, and what document-level permissions cost at query time."}],cta:"Attend a Sovereign AI Bootcamp."
  },
  "legal/privacy": {title:"Privacy — Plain language",description:"How Neurologic AI handles website visitor data.",label:"Legal & trust",hero:"Privacy should be readable.",intro:"This website does not use third-party advertising pixels, sell visitor data, or follow you around the internet.",accent:"paper",blocks:[{label:"WHAT WE COLLECT",title:"Only what is needed to respond.",body:"If you submit a briefing request, we collect the information you provide so a human can reply. Basic privacy-respecting operational logs may be retained for security and reliability."},{label:"HOW WE USE IT",title:"One purpose. No resale.",body:"We use submitted information to respond to your request, prepare the requested session, and maintain necessary business records. We do not sell it."},{label:"YOUR CHOICES",title:"Access, correction, and deletion.",body:"Contact privacy@neurologicai.com to request access, correction, or deletion, subject to applicable legal retention obligations."}],cta:"Questions about privacy? Ask us directly."},
  "legal/terms": {title:"Terms — Website use",description:"Terms governing use of the Corporate GPT website.",label:"Legal & trust",hero:"Terms, without theatre.",intro:"This site provides general information about Neurologic AI and Corporate GPT. Product commitments belong in signed agreements, not browser tabs.",accent:"paper",blocks:[{label:"INFORMATION",title:"Accurate, but not a contract.",body:"We work to keep published information accurate. Modeled figures are identified as modeled; customer claims may be anonymized or subject to public-name approval."},{label:"INTELLECTUAL PROPERTY",title:"Our materials remain ours.",body:"Site content, design, and marks are owned by Neurologic AI or their respective licensors. Reasonable internal evaluation use is welcome."},{label:"CONTACT",title:"A human answers legal questions.",body:"Write to legal@neurologicai.com for formal notices or questions."}],cta:"Need contractual detail? Put it on the briefing agenda."},
  "legal/subprocessors": {title:"Subprocessors — Short on purpose",description:"The short list of providers supporting this website.",label:"Legal & trust",hero:"This list is short on purpose.",intro:"The product is designed to run inside the customer perimeter. Customer deployment subprocessors depend on the deployment model and are documented contractually.",accent:"paper",blocks:[{label:"WEBSITE",title:"Infrastructure, kept minimal.",items:[{title:"Hosting infrastructure",body:"Serves this website and its static assets."},{title:"Business email",body:"Routes briefing requests to the team when submission infrastructure is enabled."}]},{label:"PRODUCT DEPLOYMENTS",title:"Your environment determines the list.",body:"Customer-managed and air-gapped deployments can eliminate vendor-side data subprocessors entirely. The applicable list is stated in each customer agreement."}],cta:"Ask for the subprocessor architecture for your deployment."
  }
};
